	Ext[0] = TextDrawCreate(193.166442, 132.066635, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[0], 0.000000, 0.000000);
	TextDrawTextSize(Ext[0], 128.666763, 224.415405);
	TextDrawAlignment(Ext[0], 1);
	TextDrawColor(Ext[0], 336860415);
	TextDrawSetShadow(Ext[0], 0);
	TextDrawSetOutline(Ext[0], 0);
	TextDrawFont(Ext[0], 4);


	Ext[1] = TextDrawCreate(249.833236, 132.292480, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[1], 0.000000, 0.000000);
	TextDrawTextSize(Ext[1], 71.000053, 20.326021);
	TextDrawAlignment(Ext[1], 1);
	TextDrawColor(Ext[1], -37548801);
	TextDrawSetShadow(Ext[1], 0);
	TextDrawSetOutline(Ext[1], 0);
	TextDrawFont(Ext[1], 4);

	Ext[2] = TextDrawCreate(194.166793, 152.288879, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[2], 0.000000, 0.000000);
	TextDrawTextSize(Ext[2], 127.333328, 1.244541);
	TextDrawAlignment(Ext[2], 1);
	TextDrawColor(Ext[2], -37548801);
	TextDrawSetShadow(Ext[2], 0);
	TextDrawSetOutline(Ext[2], 0);
	TextDrawFont(Ext[2], 4);

	Ext[3] = TextDrawCreate(266.833557, 138.133377, "exchange"); // just text player
	TextDrawLetterSize(Ext[3], 0.182328, 1.077334);
	TextDrawAlignment(Ext[3], 1);
	TextDrawColor(Ext[3], 336860415);
	TextDrawSetShadow(Ext[3], 0);
	TextDrawSetOutline(Ext[3], 0);
	TextDrawBackgroundColor(Ext[3], 255);
	TextDrawFont(Ext[3], 2);
	TextDrawSetProportional(Ext[3], 1);

	Ext[4] = TextDrawCreate(222.333541, 174.522186, "you"); // name of player
	TextDrawLetterSize(Ext[4], 0.149993, 0.969479);
	TextDrawAlignment(Ext[4], 2);
	TextDrawColor(Ext[4], -37548801);
	TextDrawSetShadow(Ext[4], 0);
	TextDrawSetOutline(Ext[4], 0);
	TextDrawBackgroundColor(Ext[4], 255);
	TextDrawFont(Ext[4], 2);
	TextDrawSetProportional(Ext[4], 1);

	Ext[5] = TextDrawCreate(195.833312, 221.481445, "LD_SPAC:white"); // box ok
	TextDrawLetterSize(Ext[5], 0.000000, 0.000000);
	TextDrawTextSize(Ext[5], 60.999984, 21.570350);
	TextDrawAlignment(Ext[5], 1);
	TextDrawColor(Ext[5], -37548801);
	TextDrawSetShadow(Ext[5], 0);
	TextDrawSetOutline(Ext[5], 0);
	TextDrawFont(Ext[5], 4);

	Ext[6] = TextDrawCreate(258.499908, 245.125900, "LD_SPAC:white"); // box close
	TextDrawLetterSize(Ext[6], 0.000000, 0.000000);
	TextDrawTextSize(Ext[6], 60.999984, 21.570350);
	TextDrawAlignment(Ext[6], 1);
	TextDrawColor(Ext[6], -962850561);
	TextDrawUseBox(Ext[6], true);
	TextDrawBoxColor(Ext[6], 255);
	TextDrawSetShadow(Ext[6], 0);
	TextDrawSetOutline(Ext[6], 0);
	TextDrawFont(Ext[6], 4);
	TextDrawSetSelectable(Ext[6], true);

	Ext[7] = TextDrawCreate(194.333435, 353.474029, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[7], 0.000000, 0.000000);
	TextDrawTextSize(Ext[7], 127.666687, 1.244541);
	TextDrawAlignment(Ext[7], 1);
	TextDrawColor(Ext[7], -37548801);
	TextDrawSetShadow(Ext[7], 0);
	TextDrawSetOutline(Ext[7], 0);
	TextDrawFont(Ext[7], 4);

	Ext[8] = TextDrawCreate(194.333450, 356.292572, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[8], 0.000000, 0.000000);
	TextDrawTextSize(Ext[8], 127.666687, 1.244541);
	TextDrawAlignment(Ext[8], 1);
	TextDrawColor(Ext[8], -37548801);
	TextDrawSetShadow(Ext[8], 0);
	TextDrawSetOutline(Ext[8], 0);
	TextDrawFont(Ext[8], 4);

	Ext[9] = TextDrawCreate(193.333435, 152.288879, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Ext[9], 0.000000, 0.000000);
	TextDrawTextSize(Ext[9], 1.000023, 204.918624);
	TextDrawAlignment(Ext[9], 1);
	TextDrawColor(Ext[9], -37548801);
	TextDrawSetShadow(Ext[9], 0);
	TextDrawSetOutline(Ext[9], 0);
	TextDrawFont(Ext[9], 4);

	Ext[10] = TextDrawCreate(255.833374, 342.051910, "check the information and confirm"); // text click on an object to interact with it
	TextDrawLetterSize(Ext[10], 0.131990, 0.811846);
	TextDrawAlignment(Ext[10], 2);
	TextDrawColor(Ext[10], 623191551);
	TextDrawSetShadow(Ext[10], 0);
	TextDrawSetOutline(Ext[10], 0);
	TextDrawBackgroundColor(Ext[10], 255);
	TextDrawFont(Ext[10], 2);
	TextDrawSetProportional(Ext[10], 1);

	Ext[11] = TextDrawCreate(258.666564, 221.151840, "LD_SPAC:white"); // box set money
	TextDrawLetterSize(Ext[11], 0.000000, 0.000000);
	TextDrawTextSize(Ext[11], 60.999984, 21.570350);
	TextDrawAlignment(Ext[11], 1);
	TextDrawColor(Ext[11], -37548801);
	TextDrawUseBox(Ext[11], true);
	TextDrawBoxColor(Ext[11], 255);
	TextDrawSetShadow(Ext[11], 0);
	TextDrawSetOutline(Ext[11], 0);
	TextDrawFont(Ext[11], 4);
	TextDrawSetSelectable(Ext[11], true);

	Ext[12] = TextDrawCreate(289.666656, 251.207382, "exit"); // text click on an object to interact with it
	TextDrawLetterSize(Ext[12], 0.156323, 1.052438);
	TextDrawAlignment(Ext[12], 2);
	TextDrawColor(Ext[12], 623191551);
	TextDrawSetShadow(Ext[12], 0);
	TextDrawSetOutline(Ext[12], 0);
	TextDrawBackgroundColor(Ext[12], 255);
	TextDrawFont(Ext[12], 2);
	TextDrawSetProportional(Ext[12], 1);

	Ext[13] = TextDrawCreate(224.999969, 227.148117, "ok"); // text click on an object to interact with it
	TextDrawLetterSize(Ext[13], 0.156323, 1.052438);
	TextDrawAlignment(Ext[13], 2);
	TextDrawColor(Ext[13], 623191551);
	TextDrawSetShadow(Ext[13], 0);
	TextDrawSetOutline(Ext[13], 0);
	TextDrawBackgroundColor(Ext[13], 255);
	TextDrawFont(Ext[13], 2);
	TextDrawSetProportional(Ext[13], 1);

	Ext[14] = TextDrawCreate(290.666656, 227.562942, "set price"); // text click on an object to interact with it
	TextDrawLetterSize(Ext[14], 0.156323, 1.052438);
	TextDrawAlignment(Ext[14], 2);
	TextDrawColor(Ext[14], 623191551);
	TextDrawSetShadow(Ext[14], 0);
	TextDrawSetOutline(Ext[14], 0);
	TextDrawBackgroundColor(Ext[14], 255);
	TextDrawFont(Ext[14], 2);
	TextDrawSetProportional(Ext[14], 1);

	Ext[15] = TextDrawCreate(224.666702, 251.622222, "cancel"); // text click on an object to interact with it
	TextDrawLetterSize(Ext[15], 0.156323, 1.052438);
	TextDrawAlignment(Ext[15], 2);
	TextDrawColor(Ext[15], 623191551);
	TextDrawSetShadow(Ext[15], 0);
	TextDrawSetOutline(Ext[15], 0);
	TextDrawBackgroundColor(Ext[15], 255);
	TextDrawFont(Ext[15], 2);
	TextDrawSetProportional(Ext[15], 1);
		
    PressH[0] = TextDrawCreate(497.833312, 99.896316, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(PressH[0], 0.000000, 0.000000);
	TextDrawTextSize(PressH[0], 109.999992, 14.103708);
	TextDrawAlignment(PressH[0], 1);
	TextDrawColor(PressH[0], -36827905);
	TextDrawSetShadow(PressH[0], 0);
	TextDrawSetOutline(PressH[0], 0);
	TextDrawFont(PressH[0], 4);

	PressH[1] = TextDrawCreate(497.833343, 111.925918, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(PressH[1], 0.000000, 0.000000);
	TextDrawTextSize(PressH[1], 109.999992, 2.074074);
	TextDrawAlignment(PressH[1], 1);
	TextDrawColor(PressH[1], 255);
	TextDrawSetShadow(PressH[1], 0);
	TextDrawSetOutline(PressH[1], 0);
	TextDrawBackgroundColor(PressH[1], 255);
	TextDrawFont(PressH[1], 4);

	PressH[2] = TextDrawCreate(497.833343, 114.511100, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(PressH[2], 0.000000, 0.000000);
	TextDrawTextSize(PressH[2], 109.999992, 0.829630);
	TextDrawAlignment(PressH[2], 1);
	TextDrawColor(PressH[2], 255);
	TextDrawSetShadow(PressH[2], 0);
	TextDrawSetOutline(PressH[2], 0);
	TextDrawFont(PressH[2], 4);

    Tuning[0] = TextDrawCreate(17.000000, 120.711135, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[0], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[0], 117.000000, 226.903732);
	TextDrawAlignment(Tuning[0], 1);
	TextDrawColor(Tuning[0], 336860415);
	TextDrawSetShadow(Tuning[0], 0);
	TextDrawSetOutline(Tuning[0], 0);
	TextDrawFont(Tuning[0], 4);

	Tuning[1] = TextDrawCreate(82.333328, 120.625907, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[1], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[1], 48.666694, 18.251844);
	TextDrawAlignment(Tuning[1], 1);
	TextDrawColor(Tuning[1], -36827905);
	TextDrawSetShadow(Tuning[1], 0);
	TextDrawSetOutline(Tuning[1], 0);
	TextDrawFont(Tuning[1], 4);

	Tuning[2] = TextDrawCreate(16.833311, 137.707397, "LD_SPAC:white"); // box decorative
	TextDrawLetterSize(Tuning[2], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[2], 114.400032, 1.078516);
	TextDrawAlignment(Tuning[2], 1);
	TextDrawColor(Tuning[2], -36827905);
	TextDrawSetShadow(Tuning[2], 0);
	TextDrawSetOutline(Tuning[2], 0);
	TextDrawFont(Tuning[2], 4);

	Tuning[3] = TextDrawCreate(91.333358, 124.029640, "tuning"); // Text element
	TextDrawLetterSize(Tuning[3], 0.195997, 1.193480);
	TextDrawAlignment(Tuning[3], 1);
	TextDrawColor(Tuning[3], 336860415);
	TextDrawSetShadow(Tuning[3], 0);
	TextDrawSetOutline(Tuning[3], 0);
	TextDrawBackgroundColor(Tuning[3], 255);
	TextDrawFont(Tuning[3], 2);
	TextDrawSetProportional(Tuning[3], 1);

	Tuning[4] = TextDrawCreate(73.833358, 142.696365, "vinyl"); // Text element
	TextDrawLetterSize(Tuning[4], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[4], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[4], 2);
	TextDrawColor(Tuning[4], 623191551);
	TextDrawUseBox(Tuning[4], true);
	TextDrawBoxColor(Tuning[4], -37548801);
	TextDrawSetShadow(Tuning[4], 0);
	TextDrawSetOutline(Tuning[4], 0);
	TextDrawBackgroundColor(Tuning[4], 255);
	TextDrawFont(Tuning[4], 2);
	TextDrawSetProportional(Tuning[4], 1);
	TextDrawSetSelectable(Tuning[4], true);

	Tuning[5] = TextDrawCreate(73.833358, 157.366744, "wheels"); // Text element
	TextDrawLetterSize(Tuning[5], 0.160329, 1.048297);
	TextDrawTextSize(Tuning[5], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[5], 2);
	TextDrawColor(Tuning[5], 623191551);
	TextDrawUseBox(Tuning[5], true);
	TextDrawBoxColor(Tuning[5], -222690561);
	TextDrawSetShadow(Tuning[5], 0);
	TextDrawSetOutline(Tuning[5], 0);
	TextDrawBackgroundColor(Tuning[5], -222690815);
	TextDrawFont(Tuning[5], 2);
	TextDrawSetProportional(Tuning[5], 1);
	TextDrawSetSelectable(Tuning[5], true);

	Tuning[6] = TextDrawCreate(73.833358, 172.366744, "nitrogen"); // Text element
	TextDrawLetterSize(Tuning[6], 0.160330, 1.048297);
	TextDrawTextSize(Tuning[6], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[6], 2);
	TextDrawColor(Tuning[6], 623191551);
	TextDrawUseBox(Tuning[6], true);
	TextDrawBoxColor(Tuning[6], -475069697);
	TextDrawSetShadow(Tuning[6], 0);
	TextDrawSetOutline(Tuning[6], 0);
	TextDrawBackgroundColor(Tuning[6], 255);
	TextDrawFont(Tuning[6], 2);
	TextDrawSetProportional(Tuning[6], 1);
	TextDrawSetSelectable(Tuning[6], true);

	Tuning[7] = TextDrawCreate(73.833358, 187.366744, "hydraulics"); // Text element
	TextDrawLetterSize(Tuning[7], 0.160330, 1.048297);
	TextDrawTextSize(Tuning[7], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[7], 2);
	TextDrawColor(Tuning[7], 623191551);
	TextDrawUseBox(Tuning[7], true);
	TextDrawBoxColor(Tuning[7], -559217921);
	TextDrawSetShadow(Tuning[7], 0);
	TextDrawSetOutline(Tuning[7], 0);
	TextDrawBackgroundColor(Tuning[7], 255);
	TextDrawFont(Tuning[7], 2);
	TextDrawSetProportional(Tuning[7], 1);
	TextDrawSetSelectable(Tuning[7], true);

	Tuning[8] = TextDrawCreate(73.833358, 202.366744, "hood"); // Text element
	TextDrawLetterSize(Tuning[8], 0.160329, 1.048297);
	TextDrawTextSize(Tuning[8], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[8], 2);
	TextDrawColor(Tuning[8], 623191551);
	TextDrawUseBox(Tuning[8], true);
	TextDrawBoxColor(Tuning[8], -643366145);
	TextDrawSetShadow(Tuning[8], 0);
	TextDrawSetOutline(Tuning[8], 0);
	TextDrawBackgroundColor(Tuning[8], 255);
	TextDrawFont(Tuning[8], 2);
	TextDrawSetProportional(Tuning[8], 1);
	TextDrawSetSelectable(Tuning[8], true);

	Tuning[9] = TextDrawCreate(73.833358, 216.951934, "ventilation"); // Text element
	TextDrawLetterSize(Tuning[9], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[9], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[9], 2);
	TextDrawColor(Tuning[9], 623191551);
	TextDrawUseBox(Tuning[9], true);
	TextDrawBoxColor(Tuning[9], -727514369);
	TextDrawSetShadow(Tuning[9], 0);
	TextDrawSetOutline(Tuning[9], 0);
	TextDrawBackgroundColor(Tuning[9], 255);
	TextDrawFont(Tuning[9], 2);
	TextDrawSetProportional(Tuning[9], 1);
	TextDrawSetSelectable(Tuning[9], true);

	Tuning[10] = TextDrawCreate(73.833358, 231.537124, "headlights"); // Text element
	TextDrawLetterSize(Tuning[10], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[10], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[10], 2);
	TextDrawColor(Tuning[10], 623191551);
	TextDrawUseBox(Tuning[10], true);
	TextDrawBoxColor(Tuning[10], -895810817);
	TextDrawSetShadow(Tuning[10], 0);
	TextDrawSetOutline(Tuning[10], 0);
	TextDrawBackgroundColor(Tuning[10], 255);
	TextDrawFont(Tuning[10], 2);
	TextDrawSetProportional(Tuning[10], 1);
	TextDrawSetSelectable(Tuning[10], true);

	Tuning[11] = TextDrawCreate(73.833358, 246.055633, "exhaust"); // Text element
	TextDrawLetterSize(Tuning[11], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[11], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[11], 2);
	TextDrawColor(Tuning[11], 623191551);
	TextDrawUseBox(Tuning[11], true);
	TextDrawBoxColor(Tuning[11], -1064041729);
	TextDrawSetShadow(Tuning[11], 0);
	TextDrawSetOutline(Tuning[11], 0);
	TextDrawBackgroundColor(Tuning[11], 255);
	TextDrawFont(Tuning[11], 2);
	TextDrawSetProportional(Tuning[11], 1);
	TextDrawSetSelectable(Tuning[11], true);

	Tuning[12] = TextDrawCreate(73.833351, 260.659423, "roof"); // Text element
	TextDrawLetterSize(Tuning[12], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[12], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[12], 2);
	TextDrawColor(Tuning[12], 623191551);
	TextDrawUseBox(Tuning[12], true);
	TextDrawBoxColor(Tuning[12], -1232338177);
	TextDrawSetShadow(Tuning[12], 0);
	TextDrawSetOutline(Tuning[12], 0);
	TextDrawBackgroundColor(Tuning[12], 255);
	TextDrawFont(Tuning[12], 2);
	TextDrawSetProportional(Tuning[12], 1);
	TextDrawSetSelectable(Tuning[12], true);

	Tuning[13] = TextDrawCreate(73.833358, 275.592773, "front bumper"); // Text element
	TextDrawLetterSize(Tuning[13], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[13], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[13], 2);
	TextDrawColor(Tuning[13], 623191551);
	TextDrawUseBox(Tuning[13], true);
	TextDrawBoxColor(Tuning[13], -1316486401);
	TextDrawSetShadow(Tuning[13], 0);
	TextDrawSetOutline(Tuning[13], 0);
	TextDrawBackgroundColor(Tuning[13], 255);
	TextDrawFont(Tuning[13], 2);
	TextDrawSetProportional(Tuning[13], 1);
	TextDrawSetSelectable(Tuning[13], true);

	Tuning[14] = TextDrawCreate(73.833358, 290.526062, "back bumper"); // Text element
	TextDrawLetterSize(Tuning[14], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[14], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[14], 2);
	TextDrawColor(Tuning[14], 623191551);
	TextDrawUseBox(Tuning[14], true);
	TextDrawBoxColor(Tuning[14], -1484782849);
	TextDrawSetShadow(Tuning[14], 0);
	TextDrawSetOutline(Tuning[14], 0);
	TextDrawBackgroundColor(Tuning[14], 255);
	TextDrawFont(Tuning[14], 2);
	TextDrawSetProportional(Tuning[14], 1);
	TextDrawSetSelectable(Tuning[14], true);

	Tuning[15] = TextDrawCreate(73.833358, 305.459411, "side skirts"); // Text element
	TextDrawLetterSize(Tuning[15], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[15], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[15], 2);
	TextDrawColor(Tuning[15], 623191551);
	TextDrawUseBox(Tuning[15], true);
	TextDrawBoxColor(Tuning[15], -1653079297);
	TextDrawSetShadow(Tuning[15], 0);
	TextDrawSetOutline(Tuning[15], 0);
	TextDrawBackgroundColor(Tuning[15], 255);
	TextDrawFont(Tuning[15], 2);
	TextDrawSetProportional(Tuning[15], 1);
	TextDrawSetSelectable(Tuning[15], true);

	Tuning[16] = TextDrawCreate(73.833358, 320.392883, "spoiler"); // Text element
	TextDrawLetterSize(Tuning[16], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[16], 60.666652, 111.170402);
	TextDrawAlignment(Tuning[16], 2);
	TextDrawColor(Tuning[16], 623191551);
	TextDrawUseBox(Tuning[16], true);
	TextDrawBoxColor(Tuning[16], -1838087681);
	TextDrawSetShadow(Tuning[16], 0);
	TextDrawSetOutline(Tuning[16], 0);
	TextDrawBackgroundColor(Tuning[16], 255);
	TextDrawFont(Tuning[16], 2);
	TextDrawSetProportional(Tuning[16], 1);
	TextDrawSetSelectable(Tuning[16], true);

	Tuning[17] = TextDrawCreate(132.333312, 120.540740, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[17], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[17], 1.666692, 226.903656);
	TextDrawAlignment(Tuning[17], 1);
	TextDrawColor(Tuning[17], -36827905);
	TextDrawSetShadow(Tuning[17], 0);
	TextDrawSetOutline(Tuning[17], 0);
	TextDrawFont(Tuning[17], 4);

	Tuning[18] = TextDrawCreate(130.999969, 120.540725, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[18], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[18], 1.666692, 18.251802);
	TextDrawAlignment(Tuning[18], 1);
	TextDrawColor(Tuning[18], -36827905);
	TextDrawSetShadow(Tuning[18], 0);
	TextDrawSetOutline(Tuning[18], 0);
	TextDrawFont(Tuning[18], 4);

	Tuning[19] = TextDrawCreate(133.833312, 331.799896, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[19], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[19], 55.333358, 15.762913);
	TextDrawAlignment(Tuning[19], 1);
	TextDrawColor(Tuning[19], -36827905);
	TextDrawSetShadow(Tuning[19], 0);
	TextDrawSetOutline(Tuning[19], 0);
	TextDrawFont(Tuning[19], 4);

	Tuning[20] = TextDrawCreate(27.833354, 335.170440, "select the desired parameter"); // Text element
	TextDrawLetterSize(Tuning[20], 0.138332, 0.890666);
	TextDrawAlignment(Tuning[20], 1);
	TextDrawColor(Tuning[20], 623191551);
	TextDrawSetShadow(Tuning[20], 0);
	TextDrawSetOutline(Tuning[20], 0);
	TextDrawBackgroundColor(Tuning[20], 255);
	TextDrawFont(Tuning[20], 2);
	TextDrawSetProportional(Tuning[20], 1);

	Tuning[21] = TextDrawCreate(145.333328, 312.685058, "<<"); // Text element
	TextDrawLetterSize(Tuning[21], 0.196998, 1.077332);
	TextDrawAlignment(Tuning[21], 1);
	TextDrawColor(Tuning[21], -1);
	TextDrawUseBox(Tuning[21], true);
	TextDrawBoxColor(Tuning[21], 0);
	TextDrawSetShadow(Tuning[21], 0);
	TextDrawSetOutline(Tuning[21], 0);
	TextDrawBackgroundColor(Tuning[21], -256);
	TextDrawFont(Tuning[21], 3);
	TextDrawSetProportional(Tuning[21], 1);

	Tuning[22] = TextDrawCreate(173.333328, 312.685058, ">>"); // Text element
	TextDrawLetterSize(Tuning[22], 0.196998, 1.077332);
	TextDrawAlignment(Tuning[22], 1);
	TextDrawColor(Tuning[22], -1);
	TextDrawUseBox(Tuning[22], true);
	TextDrawBoxColor(Tuning[22], 0);
	TextDrawSetShadow(Tuning[22], 0);
	TextDrawSetOutline(Tuning[22], 0);
	TextDrawBackgroundColor(Tuning[22], -256);
	TextDrawFont(Tuning[22], 3);
	TextDrawSetProportional(Tuning[22], 1);

	Tuning[23] = TextDrawCreate(140.666717, 336.000030, "select color"); // Text element
	TextDrawLetterSize(Tuning[23], 0.138332, 0.890666);
	TextDrawAlignment(Tuning[23], 1);
	TextDrawColor(Tuning[23], 623191551);
	TextDrawSetShadow(Tuning[23], 0);
	TextDrawSetOutline(Tuning[23], 0);
	TextDrawBackgroundColor(Tuning[23], 255);
	TextDrawFont(Tuning[23], 2);
	TextDrawSetProportional(Tuning[23], 1);

	Tuning[24] = TextDrawCreate(145.166641, 414.388854, "LD_SPAC:white"); // box decorative
	TextDrawLetterSize(Tuning[24], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[24], 115.066703, 1.078516);
	TextDrawAlignment(Tuning[24], 1);
	TextDrawColor(Tuning[24], 1640450303);
	TextDrawSetShadow(Tuning[24], 0);
	TextDrawSetOutline(Tuning[24], 0);
	TextDrawFont(Tuning[24], 4);

	Tuning[25] = TextDrawCreate(221.666687, 418.048156, "safety"); // Text element
	TextDrawLetterSize(Tuning[25], 0.195997, 1.193480);
	TextDrawAlignment(Tuning[25], 1);
	TextDrawColor(Tuning[25], 336860415);
	TextDrawSetShadow(Tuning[25], 0);
	TextDrawSetOutline(Tuning[25], 0);
	TextDrawBackgroundColor(Tuning[25], 255);
	TextDrawFont(Tuning[25], 2);
	TextDrawSetProportional(Tuning[25], 1);

	Tuning[26] = TextDrawCreate(145.333404, 361.218414, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[26], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[26], 115.000053, 70.933326);
	TextDrawAlignment(Tuning[26], 1);
	TextDrawColor(Tuning[26], 1640450303);
	TextDrawSetShadow(Tuning[26], 0);
	TextDrawSetOutline(Tuning[26], 0);
	TextDrawFont(Tuning[26], 4);

	Tuning[27] = TextDrawCreate(146.166748, 361.218414, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[27], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[27], 114.000061, 53.096290);
	TextDrawAlignment(Tuning[27], 1);
	TextDrawColor(Tuning[27], 336860415);
	TextDrawSetShadow(Tuning[27], 0);
	TextDrawSetOutline(Tuning[27], 0);
	TextDrawFont(Tuning[27], 4);

	Tuning[28] = TextDrawCreate(145.166763, 414.314666, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Tuning[28], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[28], 68.333351, 17.837036);
	TextDrawAlignment(Tuning[28], 1);
	TextDrawColor(Tuning[28], 336860415);
	TextDrawSetShadow(Tuning[28], 0);
	TextDrawSetOutline(Tuning[28], 0);
	TextDrawFont(Tuning[28], 4);

	Tuning[29] = TextDrawCreate(145.166641, 414.388854, "LD_SPAC:white"); // box decorative
	TextDrawLetterSize(Tuning[29], 0.000000, 0.000000);
	TextDrawTextSize(Tuning[29], 115.066703, 1.078516);
	TextDrawAlignment(Tuning[29], 1);
	TextDrawColor(Tuning[29], -36827905);
	TextDrawSetShadow(Tuning[29], 0);
	TextDrawSetOutline(Tuning[29], 0);
	TextDrawFont(Tuning[29], 4);

	Tuning[30] = TextDrawCreate(204.000015, 364.377716, "gratings"); // Text element
	TextDrawLetterSize(Tuning[30], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[30], 60.000000, 110.000000);
	TextDrawAlignment(Tuning[30], 2);
	TextDrawColor(Tuning[30], 623191551);
	TextDrawUseBox(Tuning[30], true);
	TextDrawBoxColor(Tuning[30], 1640450303);
	TextDrawSetShadow(Tuning[30], 0);
	TextDrawSetOutline(Tuning[30], 0);
	TextDrawBackgroundColor(Tuning[30], 255);
	TextDrawFont(Tuning[30], 2);
	TextDrawSetProportional(Tuning[30], 1);
	TextDrawSetSelectable(Tuning[30], true);

	Tuning[31] = TextDrawCreate(204.000015, 378.981475, "safety system"); // Text element
	TextDrawLetterSize(Tuning[31], 0.160328, 1.048297);
	TextDrawTextSize(Tuning[31], 60.000000, 110.000000);
	TextDrawAlignment(Tuning[31], 2);
	TextDrawColor(Tuning[31], 623191551);
	TextDrawUseBox(Tuning[31], true);
	TextDrawBoxColor(Tuning[31], 1640450303);
	TextDrawSetShadow(Tuning[31], 0);
	TextDrawSetOutline(Tuning[31], 0);
	TextDrawBackgroundColor(Tuning[31], 255);
	TextDrawFont(Tuning[31], 2);
	TextDrawSetProportional(Tuning[31], 1);
	TextDrawSetSelectable(Tuning[31], true);

	Tuning[32] = TextDrawCreate(203.166687, 394.488983, "the final detail is car safety~n~select parameter to inform"); // Text element
	TextDrawLetterSize(Tuning[32], 0.138331, 0.890666);
	TextDrawAlignment(Tuning[32], 2);
	TextDrawColor(Tuning[32], 623191551);
	TextDrawSetShadow(Tuning[32], 0);
	TextDrawSetOutline(Tuning[32], 0);
	TextDrawBackgroundColor(Tuning[32], 255);
	TextDrawFont(Tuning[32], 2);
	TextDrawSetProportional(Tuning[32], 1);

	ProgressBar[0] = TextDrawCreate(243.666702, 290.048156, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ProgressBar[0], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[0], 140.666656, 57.244430);
	TextDrawAlignment(ProgressBar[0], 1);
	TextDrawColor(ProgressBar[0], -37548801);
	TextDrawSetShadow(ProgressBar[0], 0);
	TextDrawSetOutline(ProgressBar[0], 0);
	TextDrawFont(ProgressBar[0], 4);

	ProgressBar[1] = TextDrawCreate(243.666702, 306.548156, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ProgressBar[1], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[1], 140.666671, 49.777759);
	TextDrawAlignment(ProgressBar[1], 1);
	TextDrawColor(ProgressBar[1], 336860415);
	TextDrawSetShadow(ProgressBar[1], 0);
	TextDrawSetOutline(ProgressBar[1], 0);
	TextDrawFont(ProgressBar[1], 4);

	ProgressBar[2] = TextDrawCreate(243.666671, 290.370269, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ProgressBar[2], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[2], 97.333343, 19.496295);
	TextDrawAlignment(ProgressBar[2], 1);
	TextDrawColor(ProgressBar[2], 336860415);
	TextDrawSetShadow(ProgressBar[2], 0);
	TextDrawSetOutline(ProgressBar[2], 0);
	TextDrawFont(ProgressBar[2], 4);

	ProgressBar[3] = TextDrawCreate(243.666702, 305.066589, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ProgressBar[3], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[3], 140.666671, 1.244433);
	TextDrawAlignment(ProgressBar[3], 1);
	TextDrawColor(ProgressBar[3], -37548801);
	TextDrawSetShadow(ProgressBar[3], 0);
	TextDrawSetOutline(ProgressBar[3], 0);
	TextDrawFont(ProgressBar[3], 4);

	ProgressBar[4] = TextDrawCreate(258.000000, 334.011260, "ld_beat:cross"); // Texture element
	TextDrawLetterSize(ProgressBar[4], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[4], 13.666671, 16.592584);
	TextDrawAlignment(ProgressBar[4], 1);
	TextDrawColor(ProgressBar[4], -1);
	TextDrawSetShadow(ProgressBar[4], 0);
	TextDrawSetOutline(ProgressBar[4], 0);
	TextDrawFont(ProgressBar[4], 4);
	TextDrawSetSelectable(ProgressBar[4], true);

	ProgressBar[5] = TextDrawCreate(290.666687, 334.426055, "ld_beat:triang"); // Texture element
	TextDrawLetterSize(ProgressBar[5], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[5], 13.666671, 16.592584);
	TextDrawAlignment(ProgressBar[5], 1);
	TextDrawColor(ProgressBar[5], -1);
	TextDrawSetShadow(ProgressBar[5], 0);
	TextDrawSetOutline(ProgressBar[5], 0);
	TextDrawFont(ProgressBar[5], 4);
	TextDrawSetSelectable(ProgressBar[5], true);

	ProgressBar[6] = TextDrawCreate(325.000000, 334.426055, "ld_beat:square"); // Texture element
	TextDrawLetterSize(ProgressBar[6], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[6], 13.666671, 16.592584);
	TextDrawAlignment(ProgressBar[6], 1);
	TextDrawColor(ProgressBar[6], -1);
	TextDrawSetShadow(ProgressBar[6], 0);
	TextDrawSetOutline(ProgressBar[6], 0);
	TextDrawFont(ProgressBar[6], 4);
	TextDrawSetSelectable(ProgressBar[6], true);

	ProgressBar[7] = TextDrawCreate(355.999969, 334.840850, "ld_beat:circle"); // Texture element
	TextDrawLetterSize(ProgressBar[7], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[7], 13.666671, 16.592584);
	TextDrawAlignment(ProgressBar[7], 1);
	TextDrawColor(ProgressBar[7], -1);
	TextDrawSetShadow(ProgressBar[7], 0);
	TextDrawSetOutline(ProgressBar[7], 0);
	TextDrawFont(ProgressBar[7], 4);
	TextDrawSetSelectable(ProgressBar[7], true);

	ProgressBar[8] = TextDrawCreate(346.833435, 292.859344, "progress"); // Text element
	TextDrawLetterSize(ProgressBar[8], 0.150665, 1.015112);
	TextDrawAlignment(ProgressBar[8], 1);
	TextDrawColor(ProgressBar[8], 336860415);
	TextDrawSetShadow(ProgressBar[8], 0);
	TextDrawSetOutline(ProgressBar[8], 0);
	TextDrawBackgroundColor(ProgressBar[8], 255);
	TextDrawFont(ProgressBar[8], 2);
	TextDrawSetProportional(ProgressBar[8], 1);

	ProgressBar[9] = TextDrawCreate(301.166809, 314.844482, "press"); // Text element
	TextDrawLetterSize(ProgressBar[9], 0.150665, 1.015112);
	TextDrawAlignment(ProgressBar[9], 1);
	TextDrawColor(ProgressBar[9], -1);
	TextDrawSetShadow(ProgressBar[9], 0);
	TextDrawSetOutline(ProgressBar[9], 0);
	TextDrawBackgroundColor(ProgressBar[9], 255);
	TextDrawFont(ProgressBar[9], 2);
	TextDrawSetProportional(ProgressBar[9], 1);

	ProgressBar[10] = TextDrawCreate(245.666671, 292.859252, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ProgressBar[10], 0.000000, 0.000000);
	TextDrawTextSize(ProgressBar[10], 93.333328, 9.955566);
	TextDrawAlignment(ProgressBar[10], 1);
	TextDrawColor(ProgressBar[10], -1838087681);
	TextDrawSetShadow(ProgressBar[10], 0);
	TextDrawSetOutline(ProgressBar[10], 0);
	TextDrawFont(ProgressBar[10], 4);

    AdminPanel[0] = TextDrawCreate(222.000000, 383.959197, "update"); // Text element
	TextDrawLetterSize(AdminPanel[0], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[0], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[0], 2);
	TextDrawColor(AdminPanel[0], -1);
	TextDrawUseBox(AdminPanel[0], true);
	TextDrawBoxColor(AdminPanel[0], 1640450303);
	TextDrawSetShadow(AdminPanel[0], 0);
	TextDrawSetOutline(AdminPanel[0], 0);
	TextDrawBackgroundColor(AdminPanel[0], -36827905);
	TextDrawFont(AdminPanel[0], 2);
	TextDrawSetProportional(AdminPanel[0], 1);
	TextDrawSetSelectable(AdminPanel[0], true);

	AdminPanel[1] = TextDrawCreate(222.000000, 398.959197, "stop"); // Text element
	TextDrawLetterSize(AdminPanel[1], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[1], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[1], 2);
	TextDrawColor(AdminPanel[1], -1);
	TextDrawUseBox(AdminPanel[1], true);
	TextDrawBoxColor(AdminPanel[1], -667864577);
	TextDrawSetShadow(AdminPanel[1], 0);
	TextDrawSetOutline(AdminPanel[1], 0);
	TextDrawBackgroundColor(AdminPanel[1], 51);
	TextDrawFont(AdminPanel[1], 2);
	TextDrawSetProportional(AdminPanel[1], 1);
	TextDrawSetSelectable(AdminPanel[1], true);

	AdminPanel[2] = TextDrawCreate(222.000000, 413.959197, "time"); // Text element
	TextDrawLetterSize(AdminPanel[2], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[2], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[2], 2);
	TextDrawColor(AdminPanel[2], 255);
	TextDrawUseBox(AdminPanel[2], true);
	TextDrawBoxColor(AdminPanel[2], -36827905);
	TextDrawSetShadow(AdminPanel[2], 0);
	TextDrawSetOutline(AdminPanel[2], 0);
	TextDrawBackgroundColor(AdminPanel[2], 51);
	TextDrawFont(AdminPanel[2], 2);
	TextDrawSetProportional(AdminPanel[2], 1);
	TextDrawSetSelectable(AdminPanel[2], true);

	AdminPanel[3] = TextDrawCreate(222.000000, 428.959197, "ban"); // Text element
	TextDrawLetterSize(AdminPanel[3], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[3], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[3], 2);
	TextDrawColor(AdminPanel[3], 255);
	TextDrawUseBox(AdminPanel[3], true);
	TextDrawBoxColor(AdminPanel[3], -36827905);
	TextDrawSetShadow(AdminPanel[3], 0);
	TextDrawSetOutline(AdminPanel[3], 0);
	TextDrawBackgroundColor(AdminPanel[3], 51);
	TextDrawFont(AdminPanel[3], 2);
	TextDrawSetProportional(AdminPanel[3], 1);
	TextDrawSetSelectable(AdminPanel[3], true);

	AdminPanel[4] = TextDrawCreate(263.666656, 383.999908, "next"); // Text element
	TextDrawLetterSize(AdminPanel[4], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[4], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[4], 2);
	TextDrawColor(AdminPanel[4], 255);
	TextDrawUseBox(AdminPanel[4], true);
	TextDrawBoxColor(AdminPanel[4], -36827905);
	TextDrawSetShadow(AdminPanel[4], 0);
	TextDrawSetOutline(AdminPanel[4], 0);
	TextDrawBackgroundColor(AdminPanel[4], 51);
	TextDrawFont(AdminPanel[4], 2);
	TextDrawSetProportional(AdminPanel[4], 1);
	TextDrawSetSelectable(AdminPanel[4], true);

	AdminPanel[5] = TextDrawCreate(263.666656, 398.999908, "back"); // Text element
	TextDrawLetterSize(AdminPanel[5], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[5], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[5], 2);
	TextDrawColor(AdminPanel[5], 255);
	TextDrawUseBox(AdminPanel[5], true);
	TextDrawBoxColor(AdminPanel[5], -36827905);
	TextDrawSetShadow(AdminPanel[5], 0);
	TextDrawSetOutline(AdminPanel[5], 0);
	TextDrawBackgroundColor(AdminPanel[5], 51);
	TextDrawFont(AdminPanel[5], 2);
	TextDrawSetProportional(AdminPanel[5], 1);
	TextDrawSetSelectable(AdminPanel[5], true);

	AdminPanel[6] = TextDrawCreate(263.666656, 413.585083, "warn"); // Text element
	TextDrawLetterSize(AdminPanel[6], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[6], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[6], 2);
	TextDrawColor(AdminPanel[6], 255);
	TextDrawUseBox(AdminPanel[6], true);
	TextDrawBoxColor(AdminPanel[6], -36827905);
	TextDrawSetShadow(AdminPanel[6], 0);
	TextDrawSetOutline(AdminPanel[6], 0);
	TextDrawBackgroundColor(AdminPanel[6], 51);
	TextDrawFont(AdminPanel[6], 2);
	TextDrawSetProportional(AdminPanel[6], 1);
	TextDrawSetSelectable(AdminPanel[6], true);

	AdminPanel[7] = TextDrawCreate(263.666656, 429.085083, "stats"); // Text element
	TextDrawLetterSize(AdminPanel[7], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[7], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[7], 2);
	TextDrawColor(AdminPanel[7], 255);
	TextDrawUseBox(AdminPanel[7], true);
	TextDrawBoxColor(AdminPanel[7], -36827905);
	TextDrawSetShadow(AdminPanel[7], 0);
	TextDrawSetOutline(AdminPanel[7], 0);
	TextDrawBackgroundColor(AdminPanel[7], 51);
	TextDrawFont(AdminPanel[7], 2);
	TextDrawSetProportional(AdminPanel[7], 1);
	TextDrawSetSelectable(AdminPanel[7], true);

	AdminPanel[8] = TextDrawCreate(305.333343, 384.114654, "spawn"); // Text element
	TextDrawLetterSize(AdminPanel[8], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[8], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[8], 2);
	TextDrawColor(AdminPanel[8], 255);
	TextDrawUseBox(AdminPanel[8], true);
	TextDrawBoxColor(AdminPanel[8], -36827905);
	TextDrawSetShadow(AdminPanel[8], 0);
	TextDrawSetOutline(AdminPanel[8], 0);
	TextDrawBackgroundColor(AdminPanel[8], 51);
	TextDrawFont(AdminPanel[8], 2);
	TextDrawSetProportional(AdminPanel[8], 1);
	TextDrawSetSelectable(AdminPanel[8], true);

	AdminPanel[9] = TextDrawCreate(305.333343, 398.785034, "jail"); // Text element
	TextDrawLetterSize(AdminPanel[9], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[9], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[9], 2);
	TextDrawColor(AdminPanel[9], 255);
	TextDrawUseBox(AdminPanel[9], true);
	TextDrawBoxColor(AdminPanel[9], -36827905);
	TextDrawSetShadow(AdminPanel[9], 0);
	TextDrawSetOutline(AdminPanel[9], 0);
	TextDrawBackgroundColor(AdminPanel[9], 51);
	TextDrawFont(AdminPanel[9], 2);
	TextDrawSetProportional(AdminPanel[9], 1);
	TextDrawSetSelectable(AdminPanel[9], true);

	AdminPanel[10] = TextDrawCreate(305.333343, 413.785034, "set hp"); // Text element
	TextDrawLetterSize(AdminPanel[10], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[10], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[10], 2);
	TextDrawColor(AdminPanel[10], 255);
	TextDrawUseBox(AdminPanel[10], true);
	TextDrawBoxColor(AdminPanel[10], -36827905);
	TextDrawSetShadow(AdminPanel[10], 0);
	TextDrawSetOutline(AdminPanel[10], 0);
	TextDrawBackgroundColor(AdminPanel[10], 51);
	TextDrawFont(AdminPanel[10], 2);
	TextDrawSetProportional(AdminPanel[10], 1);
	TextDrawSetSelectable(AdminPanel[10], true);

	AdminPanel[11] = TextDrawCreate(305.166656, 429.085083, "mute"); // Text element
	TextDrawLetterSize(AdminPanel[11], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[11], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[11], 2);
	TextDrawColor(AdminPanel[11], 255);
	TextDrawUseBox(AdminPanel[11], true);
	TextDrawBoxColor(AdminPanel[11], -36827905);
	TextDrawSetShadow(AdminPanel[11], 0);
	TextDrawSetOutline(AdminPanel[11], 0);
	TextDrawBackgroundColor(AdminPanel[11], 51);
	TextDrawFont(AdminPanel[11], 2);
	TextDrawSetProportional(AdminPanel[11], 1);
	TextDrawSetSelectable(AdminPanel[11], true);

	AdminPanel[12] = TextDrawCreate(537.499938, 174.433334, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[12], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[12], 97.333335, 150.992584);
	TextDrawAlignment(AdminPanel[12], 1);
	TextDrawColor(AdminPanel[12], -36827905);
	TextDrawSetShadow(AdminPanel[12], 0);
	TextDrawSetOutline(AdminPanel[12], 0);
	TextDrawFont(AdminPanel[12], 4);

	AdminPanel[13] = TextDrawCreate(538.666625, 175.763031, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[13], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[13], 94.999938, 148.503738);
	TextDrawAlignment(AdminPanel[13], 1);
	TextDrawColor(AdminPanel[13], 623191551);
	TextDrawSetShadow(AdminPanel[13], 0);
	TextDrawSetOutline(AdminPanel[13], 0);
	TextDrawFont(AdminPanel[13], 4);

	AdminPanel[14] = TextDrawCreate(539.333312, 176.507415, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[14], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[14], 93.666664, 12.444463);
	TextDrawAlignment(AdminPanel[14], 1);
	TextDrawColor(AdminPanel[14], -36827905);
	TextDrawSetShadow(AdminPanel[14], 0);
	TextDrawSetOutline(AdminPanel[14], 0);
	TextDrawFont(AdminPanel[14], 4);

	AdminPanel[15] = TextDrawCreate(547.666687, 189.781478, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[15], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[15], 85.666679, 0.829649);
	TextDrawAlignment(AdminPanel[15], 1);
	TextDrawColor(AdminPanel[15], -36827905);
	TextDrawSetShadow(AdminPanel[15], 0);
	TextDrawSetOutline(AdminPanel[15], 0);
	TextDrawFont(AdminPanel[15], 4);

	AdminPanel[16] = TextDrawCreate(346.833312, 383.955474, "fixveh"); // Text element
	TextDrawLetterSize(AdminPanel[16], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[16], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[16], 2);
	TextDrawColor(AdminPanel[16], 255);
	TextDrawUseBox(AdminPanel[16], true);
	TextDrawBoxColor(AdminPanel[16], -36827905);
	TextDrawSetShadow(AdminPanel[16], 0);
	TextDrawSetOutline(AdminPanel[16], 0);
	TextDrawBackgroundColor(AdminPanel[16], 51);
	TextDrawFont(AdminPanel[16], 2);
	TextDrawSetProportional(AdminPanel[16], 1);
	TextDrawSetSelectable(AdminPanel[16], true);

	AdminPanel[17] = TextDrawCreate(346.833312, 398.955474, "guns"); // Text element
	TextDrawLetterSize(AdminPanel[17], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[17], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[17], 2);
	TextDrawColor(AdminPanel[17], 255);
	TextDrawUseBox(AdminPanel[17], true);
	TextDrawBoxColor(AdminPanel[17], -36827905);
	TextDrawSetShadow(AdminPanel[17], 0);
	TextDrawSetOutline(AdminPanel[17], 0);
	TextDrawBackgroundColor(AdminPanel[17], 51);
	TextDrawFont(AdminPanel[17], 2);
	TextDrawSetProportional(AdminPanel[17], 1);
	TextDrawSetSelectable(AdminPanel[17], true);

	AdminPanel[18] = TextDrawCreate(346.833312, 413.955474, "check ip"); // Text element
	TextDrawLetterSize(AdminPanel[18], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[18], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[18], 2);
	TextDrawColor(AdminPanel[18], 255);
	TextDrawUseBox(AdminPanel[18], true);
	TextDrawBoxColor(AdminPanel[18], -36827905);
	TextDrawSetShadow(AdminPanel[18], 0);
	TextDrawSetOutline(AdminPanel[18], 0);
	TextDrawBackgroundColor(AdminPanel[18], 51);
	TextDrawFont(AdminPanel[18], 2);
	TextDrawSetProportional(AdminPanel[18], 1);
	TextDrawSetSelectable(AdminPanel[18], true);

	AdminPanel[19] = TextDrawCreate(346.833312, 428.955474, "kick"); // Text element
	TextDrawLetterSize(AdminPanel[19], 0.146999, 0.986073);
	TextDrawTextSize(AdminPanel[19], 28.666662, 37.333332);
	TextDrawAlignment(AdminPanel[19], 2);
	TextDrawColor(AdminPanel[19], 255);
	TextDrawUseBox(AdminPanel[19], true);
	TextDrawBoxColor(AdminPanel[19], -36827905);
	TextDrawSetShadow(AdminPanel[19], 0);
	TextDrawSetOutline(AdminPanel[19], 0);
	TextDrawBackgroundColor(AdminPanel[19], 51);
	TextDrawFont(AdminPanel[19], 2);
	TextDrawSetProportional(AdminPanel[19], 1);
	TextDrawSetSelectable(AdminPanel[19], true);

	AdminPanel[20] = TextDrawCreate(542.000000, 195.503723, "nick~n~ping~n~lvl~n~speed~n~hp~n~armour"); // Text element
	TextDrawLetterSize(AdminPanel[20], 0.147330, 1.044147);
	TextDrawAlignment(AdminPanel[20], 1);
	TextDrawColor(AdminPanel[20], -1);
	TextDrawSetShadow(AdminPanel[20], 0);
	TextDrawSetOutline(AdminPanel[20], 0);
	TextDrawBackgroundColor(AdminPanel[20], 51);
	TextDrawFont(AdminPanel[20], 2);
	TextDrawSetProportional(AdminPanel[20], 1);

	AdminPanel[21] = TextDrawCreate(538.333374, 191.355560, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[21], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[21], 78.333351, 0.829650);
	TextDrawAlignment(AdminPanel[21], 1);
	TextDrawColor(AdminPanel[21], -36827905);
	TextDrawSetShadow(AdminPanel[21], 0);
	TextDrawSetOutline(AdminPanel[21], 0);
	TextDrawFont(AdminPanel[21], 4);

	AdminPanel[22] = TextDrawCreate(542.000000, 253.003723, "car_hp~N~speed~n~ammo~n~shot~n~tshot~n~afktime~n~"); // Text element
	TextDrawLetterSize(AdminPanel[22], 0.147330, 1.044147);
	TextDrawAlignment(AdminPanel[22], 1);
	TextDrawColor(AdminPanel[22], -1936945921);
	TextDrawSetShadow(AdminPanel[22], 0);
	TextDrawSetOutline(AdminPanel[22], 0);
	TextDrawBackgroundColor(AdminPanel[22], 51);
	TextDrawFont(AdminPanel[22], 2);
	TextDrawSetProportional(AdminPanel[22], 1);

	AdminPanel[23] = TextDrawCreate(534.833129, 174.348129, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize( AdminPanel[23], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[23], -0.333340, 150.992599);
	TextDrawAlignment(AdminPanel[23], 1);
	TextDrawColor(AdminPanel[23], -36827905);
	TextDrawSetShadow( AdminPanel[23], 0);
	TextDrawSetOutline( AdminPanel[23], 0);
	TextDrawFont( AdminPanel[23], 4);

	AdminPanel[24] = TextDrawCreate(561.166625, 176.877838, "player_info"); // Text element
	TextDrawLetterSize(AdminPanel[24], 0.202329, 1.230813);
	TextDrawAlignment(AdminPanel[24], 1);
	TextDrawColor(AdminPanel[24], 255);
	TextDrawSetShadow(AdminPanel[24], 0);
	TextDrawSetOutline(AdminPanel[24], 0);
	TextDrawBackgroundColor(AdminPanel[24], 51);
	TextDrawFont(AdminPanel[24], 2);
	TextDrawSetProportional(AdminPanel[24], 1);

	AdminPanel[25] = TextDrawCreate(535.833129, 174.348129, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(AdminPanel[25], 0.000000, 0.000000);
	TextDrawTextSize(AdminPanel[25], 0.999992, 150.992599);
	TextDrawAlignment(AdminPanel[25], 1);
	TextDrawColor(AdminPanel[25], -36827905);
	TextDrawSetShadow(AdminPanel[25], 0);
	TextDrawSetOutline(AdminPanel[25], 0);
	TextDrawFont(AdminPanel[25], 4);

	Camera[0] = TextDrawCreate(7.666666, 9.540740, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[0], 0.000000, 0.000000);
	TextDrawTextSize(Camera[0], 3.000000, 73.422218);
	TextDrawAlignment(Camera[0], 1);
	TextDrawColor(Camera[0], -1);
	TextDrawSetShadow(Camera[0], 0);
	TextDrawSetOutline(Camera[0], 0);
	TextDrawFont(Camera[0], 4);

	Camera[1] = TextDrawCreate(630.333251, 9.540740, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[1], 0.000000, 0.000000);
	TextDrawTextSize(Camera[1], 3.000000, 73.422218);
	TextDrawAlignment(Camera[1], 1);
	TextDrawColor(Camera[1], -1);
	TextDrawSetShadow(Camera[1], 0);
	TextDrawSetOutline(Camera[1], 0);
	TextDrawFont(Camera[1], 4);

	Camera[2] = TextDrawCreate(630.666564, 364.833343, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[2], 0.000000, 0.000000);
	TextDrawTextSize(Camera[2], 3.000000, 73.422218);
	TextDrawAlignment(Camera[2], 1);
	TextDrawColor(Camera[2], -1);
	TextDrawSetShadow(Camera[2], 0);
	TextDrawSetOutline(Camera[2], 0);
	TextDrawFont(Camera[2], 4);

	Camera[3] = TextDrawCreate(7.499911, 364.003631, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[3], 0.000000, 0.000000);
	TextDrawTextSize(Camera[3], 3.000000, 73.422218);
	TextDrawAlignment(Camera[3], 1);
	TextDrawColor(Camera[3], -1);
	TextDrawSetShadow(Camera[3], 0);
	TextDrawSetOutline(Camera[3], 0);
	TextDrawFont(Camera[3], 4);

	Camera[4] = TextDrawCreate(8.833245, 433.692535, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[4], 0.000000, 0.000000);
	TextDrawTextSize(Camera[4], 64.666664, 3.733338);
	TextDrawAlignment(Camera[4], 1);
	TextDrawColor(Camera[4], -1);
	TextDrawSetShadow(Camera[4], 0);
	TextDrawSetOutline(Camera[4], 0);
	TextDrawFont(Camera[4], 4);

	Camera[5] = TextDrawCreate(9.333250, 9.336948, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[5], 0.000000, 0.000000);
	TextDrawTextSize(Camera[5], 64.666664, 3.733338);
	TextDrawAlignment(Camera[5], 1);
	TextDrawColor(Camera[5], -1);
	TextDrawSetShadow(Camera[5], 0);
	TextDrawSetOutline(Camera[5], 0);
	TextDrawFont(Camera[5], 4);

	Camera[6] = TextDrawCreate(567.666625, 9.336951, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[6], 0.000000, 0.000000);
	TextDrawTextSize(Camera[6], 64.666664, 3.733338);
	TextDrawAlignment(Camera[6], 1);
	TextDrawColor(Camera[6], -1);
	TextDrawSetShadow(Camera[6], 0);
	TextDrawSetOutline(Camera[6], 0);
	TextDrawFont(Camera[6], 4);

	Camera[7] = TextDrawCreate(567.333129, 434.522125, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[7], 0.000000, 0.000000);
	TextDrawTextSize(Camera[7], 64.666664, 3.733338);
	TextDrawAlignment(Camera[7], 1);
	TextDrawColor(Camera[7], -1);
	TextDrawSetShadow(Camera[7], 0);
	TextDrawSetOutline(Camera[7], 0);
	TextDrawFont(Camera[7], 4);

	Camera[8] = TextDrawCreate(306.000000, 424.599945, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[8], 0.000000, 0.000000);
	TextDrawTextSize(Camera[8], 3.000020, 14.933321);
	TextDrawAlignment(Camera[8], 1);
	TextDrawColor(Camera[8], -1);
	TextDrawSetShadow(Camera[8], 0);
	TextDrawSetOutline(Camera[8], 0);
	TextDrawFont(Camera[8], 4);

	Camera[9] = TextDrawCreate(310.666687, 424.599945, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[9], 0.000000, 0.000000);
	TextDrawTextSize(Camera[9], 3.000020, 14.933321);
	TextDrawAlignment(Camera[9], 1);
	TextDrawColor(Camera[9], -1);
	TextDrawSetShadow(Camera[9], 0);
	TextDrawSetOutline(Camera[9], 0);
	TextDrawFont(Camera[9], 4);

	Camera[10] = TextDrawCreate(317.666687, 424.770324, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[10], 0.000000, 0.000000);
	TextDrawTextSize(Camera[10], 11.666687, 14.933321);
	TextDrawAlignment(Camera[10], 1);
	TextDrawColor(Camera[10], -1);
	TextDrawSetShadow(Camera[10], 0);
	TextDrawSetOutline(Camera[10], 0);
	TextDrawFont(Camera[10], 4);

	Camera[11] = TextDrawCreate(77.333320, 430.003662, "FULL HD fps ISO200 1/250 F8.0"); // Text element
	TextDrawLetterSize(Camera[11], 0.267333, 1.272296);
	TextDrawAlignment(Camera[11], 1);
	TextDrawColor(Camera[11], -1);
	TextDrawSetShadow(Camera[11], 0);
	TextDrawSetOutline(Camera[11], 0);
	TextDrawBackgroundColor(Camera[11], 255);
	TextDrawFont(Camera[11], 1);
	TextDrawSetProportional(Camera[11], 1);

	Camera[12] = TextDrawCreate(7.333320, 350.859252, "OFF"); // Text element
	TextDrawLetterSize(Camera[12], 0.267333, 1.272296);
	TextDrawAlignment(Camera[12], 1);
	TextDrawColor(Camera[12], -1);
	TextDrawSetShadow(Camera[12], 0);
	TextDrawSetOutline(Camera[12], 0);
	TextDrawBackgroundColor(Camera[12], 255);
	TextDrawFont(Camera[12], 1);
	TextDrawSetProportional(Camera[12], 1);

	Camera[13] = TextDrawCreate(6.666654, 84.133331, "AF"); // Text element
	TextDrawLetterSize(Camera[13], 0.267333, 1.272295);
	TextDrawAlignment(Camera[13], 1);
	TextDrawColor(Camera[13], -1);
	TextDrawSetShadow(Camera[13], 0);
	TextDrawSetOutline(Camera[13], 0);
	TextDrawBackgroundColor(Camera[13], 255);
	TextDrawFont(Camera[13], 1);
	TextDrawSetProportional(Camera[13], 1);

	Camera[14] = TextDrawCreate(35.000019, 14.933340, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Camera[14], 0.000000, 0.000000);
	TextDrawTextSize(Camera[14], 15.999974, 18.666658);
	TextDrawAlignment(Camera[14], 1);
	TextDrawColor(Camera[14], -618388225);
	TextDrawSetShadow(Camera[14], 0);
	TextDrawSetOutline(Camera[14], 0);
	TextDrawFont(Camera[14], 4);

	Camera[15] = TextDrawCreate(51.166648, 15.774077, "REC"); // Text element
	TextDrawLetterSize(Camera[15], 0.383332, 1.815703);
	TextDrawAlignment(Camera[15], 1);
	TextDrawColor(Camera[15], -1);
	TextDrawSetShadow(Camera[15], 0);
	TextDrawSetOutline(Camera[15], 0);
	TextDrawBackgroundColor(Camera[15], 255);
	TextDrawFont(Camera[15], 1);
	TextDrawSetProportional(Camera[15], 1);

	Camera[16] = TextDrawCreate(583.000000, 21.751867, "Power ON"); // Text element
	TextDrawLetterSize(Camera[16], 0.252333, 1.226666);
	TextDrawAlignment(Camera[16], 1);
	TextDrawColor(Camera[16], -1);
	TextDrawSetShadow(Camera[16], 0);
	TextDrawSetOutline(Camera[16], 0);
	TextDrawBackgroundColor(Camera[16], 255);
	TextDrawFont(Camera[16], 1);
	TextDrawSetProportional(Camera[16], 1);

	Camera[17] = TextDrawCreate(631.833374, 88.462966, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[17], 0.000000, 0.000000);
	TextDrawTextSize(Camera[17], 1.333312, 270.044433);
	TextDrawAlignment(Camera[17], 1);
	TextDrawColor(Camera[17], -1);
	TextDrawSetShadow(Camera[17], 0);
	TextDrawSetOutline(Camera[17], 0);
	TextDrawFont(Camera[17], 4);

	Camera[18] = TextDrawCreate(630.333374, 88.462966, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[18], 0.000000, 0.000000);
	TextDrawTextSize(Camera[18], 2.333312, 2.074062);
	TextDrawAlignment(Camera[18], 1);
	TextDrawColor(Camera[18], -1);
	TextDrawSetShadow(Camera[18], 0);
	TextDrawSetOutline(Camera[18], 0);
	TextDrawFont(Camera[18], 4);

	Camera[19] = TextDrawCreate(630.000000, 356.433380, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[19], 0.000000, 0.000000);
	TextDrawTextSize(Camera[19], 2.333312, 2.074062);
	TextDrawAlignment(Camera[19], 1);
	TextDrawColor(Camera[19], -1);
	TextDrawSetShadow(Camera[19], 0);
	TextDrawSetOutline(Camera[19], 0);
	TextDrawFont(Camera[19], 4);

	Camera[20] = TextDrawCreate(630.000061, 217.055603, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[20], 0.000000, 0.000000);
	TextDrawTextSize(Camera[20], 2.333312, 2.074062);
	TextDrawAlignment(Camera[20], 1);
	TextDrawColor(Camera[20], -1);
	TextDrawSetShadow(Camera[20], 0);
	TextDrawSetOutline(Camera[20], 0);
	TextDrawFont(Camera[20], 4);

	Camera[21] = TextDrawCreate(629.666625, 148.122314, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[21], 0.000000, 0.000000);
	TextDrawTextSize(Camera[21], 2.333312, 2.074062);
	TextDrawAlignment(Camera[21], 1);
	TextDrawColor(Camera[21], -1);
	TextDrawSetShadow(Camera[21], 0);
	TextDrawSetOutline(Camera[21], 0);
	TextDrawFont(Camera[21], 4);

	Camera[22] = TextDrawCreate(629.666687, 287.488952, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Camera[22], 0.000000, 0.000000);
	TextDrawTextSize(Camera[22], 2.333312, 2.074062);
	TextDrawAlignment(Camera[22], 1);
	TextDrawColor(Camera[22], -1);
	TextDrawSetShadow(Camera[22], 0);
	TextDrawSetOutline(Camera[22], 0);
	TextDrawFont(Camera[22], 4);

	Camera[23] = TextDrawCreate(624.999877, 84.548164, "2"); // Text element
	TextDrawLetterSize(Camera[23], 0.208332, 1.064888);
	TextDrawAlignment(Camera[23], 1);
	TextDrawColor(Camera[23], -1);
	TextDrawSetShadow(Camera[23], 0);
	TextDrawSetOutline(Camera[23], 0);
	TextDrawBackgroundColor(Camera[23], 255);
	TextDrawFont(Camera[23], 1);
	TextDrawSetProportional(Camera[23], 1);

	Camera[24] = TextDrawCreate(624.499877, 212.396331, "0"); // Text element
	TextDrawLetterSize(Camera[24], 0.208332, 1.064888);
	TextDrawAlignment(Camera[24], 1);
	TextDrawColor(Camera[24], -1);
	TextDrawSetShadow(Camera[24], 0);
	TextDrawSetOutline(Camera[24], 0);
	TextDrawBackgroundColor(Camera[24], 255);
	TextDrawFont(Camera[24], 1);
	TextDrawSetProportional(Camera[24], 1);

	Camera[25] = TextDrawCreate(621.499816, 351.944580, "-2"); // Text element
	TextDrawLetterSize(Camera[25], 0.208332, 1.064888);
	TextDrawAlignment(Camera[25], 1);
	TextDrawColor(Camera[25], -1);
	TextDrawSetShadow(Camera[25], 0);
	TextDrawSetOutline(Camera[25], 0);
	TextDrawBackgroundColor(Camera[25], 255);
	TextDrawFont(Camera[25], 1);
	TextDrawSetProportional(Camera[25], 1);

	Camera[26] = TextDrawCreate(11.999985, 362.559417, "awb mode"); // Text element
	TextDrawLetterSize(Camera[26], 0.209666, 1.048296);
	TextDrawAlignment(Camera[26], 1);
	TextDrawColor(Camera[26], -1);
	TextDrawSetShadow(Camera[26], 0);
	TextDrawSetOutline(Camera[26], 0);
	TextDrawBackgroundColor(Camera[26], 255);
	TextDrawFont(Camera[26], 1);
	TextDrawSetProportional(Camera[26], 1);

	Auction[0] = TextDrawCreate(406.000122, 357.740692, "box"); // Box element
	TextDrawLetterSize(Auction[0], 0.000000, 6.570573);
	TextDrawTextSize(Auction[0], 232.999938, -0.500000);
	TextDrawAlignment(Auction[0], 1);
	TextDrawColor(Auction[0], 623191551);
	TextDrawUseBox(Auction[0], true);
	TextDrawBoxColor(Auction[0], 623191551);
	TextDrawSetShadow(Auction[0], 0);
	TextDrawSetOutline(Auction[0], 0);
	TextDrawFont(Auction[0], 0);

	Auction[1] = TextDrawCreate(405.999969, 337.177764, "box"); // Box element
	TextDrawLetterSize(Auction[1], 0.000000, 1.137238);
	TextDrawTextSize(Auction[1], 230.999969, -16.500000);
	TextDrawAlignment(Auction[1], 1);
	TextDrawColor(Auction[1], 623191551);
	TextDrawUseBox(Auction[1], true);
	TextDrawBoxColor(Auction[1], -36827905);
	TextDrawSetShadow(Auction[1], 0);
	TextDrawSetOutline(Auction[1], 0);
	TextDrawFont(Auction[1], 0);

	Auction[2]  = TextDrawCreate(238.333312, 337.381439, "auction participant"); // Text element
	TextDrawLetterSize(Auction[2] , 0.183666, 1.143704);
	TextDrawAlignment(Auction[2] , 1);
	TextDrawColor(Auction[2] , 623191551);
	TextDrawSetShadow(Auction[2] , 0);
	TextDrawSetOutline(Auction[2] , 0);
	TextDrawBackgroundColor(Auction[2] , 623191551);
	TextDrawFont(Auction[2] , 2);
	TextDrawSetProportional(Auction[2] , 1);

	Auction[3] = TextDrawCreate(410.500061, 351.781463, "box"); // Box element
	TextDrawLetterSize(Auction[3], 0.000000, -0.196088);
	TextDrawTextSize(Auction[3], 232.833267, -16.000000);
	TextDrawAlignment(Auction[3], 1);
	TextDrawColor(Auction[3], -36827905);
	TextDrawUseBox(Auction[3], true);
	TextDrawBoxColor(Auction[3], -36827905);
	TextDrawSetShadow(Auction[3], 0);
	TextDrawSetOutline(Auction[3], 0);
	TextDrawBackgroundColor(Auction[3], -36827905);
	TextDrawFont(Auction[3], 0);


	Auction[4] = TextDrawCreate(233.333358, 336.848052, "box"); // Box element
	TextDrawLetterSize(Auction[4], 0.000000, 9.537240);
	TextDrawTextSize(Auction[4], 231.666610, -16.000000);
	TextDrawAlignment(Auction[4], 1);
	TextDrawColor(Auction[4], -36827905);
	TextDrawUseBox(Auction[4], true);
	TextDrawBoxColor(Auction[4], -36827905);
	TextDrawSetShadow(Auction[4], 0);
	TextDrawSetOutline(Auction[4], 0);
	TextDrawBackgroundColor(Auction[4], -36827905);
	TextDrawFont(Auction[4], 0);

	Auction[5] = TextDrawCreate(235.000015, 338.114746, "box"); // Box element
	TextDrawLetterSize(Auction[5], 0.000000, 8.737235);
	TextDrawTextSize(Auction[5], 233.333267, -11.000000);
	TextDrawAlignment(Auction[5], 1);
	TextDrawColor(Auction[5], -36827905);
	TextDrawUseBox(Auction[5], true);
	TextDrawBoxColor(Auction[5], -36827905);
	TextDrawSetShadow(Auction[5], 0);
	TextDrawSetOutline(Auction[5], 0);
	TextDrawBackgroundColor(Auction[5], -36827905);
	TextDrawFont(Auction[5], 0);

	Auction[6] = TextDrawCreate(405.833465, 354.281463, "box"); // Box element
	TextDrawLetterSize(Auction[6], 0.000000, -0.196088);
	TextDrawTextSize(Auction[6], 232.833267, -13.500000);
	TextDrawAlignment(Auction[6], 1);
	TextDrawColor(Auction[6], -36827905);
	TextDrawUseBox(Auction[6], true);
	TextDrawBoxColor(Auction[6], -36827905);
	TextDrawSetShadow(Auction[6], 0);
	TextDrawSetOutline(Auction[6], 0);
	TextDrawBackgroundColor(Auction[6], -36827905);
	TextDrawFont(Auction[6], 0);



	Auction[7] = TextDrawCreate(372.666687, 336.966613, "bet, $"); // Text element
	TextDrawLetterSize(Auction[7], 0.183666, 1.143704);
	TextDrawAlignment(Auction[7], 1);
	TextDrawColor(Auction[7], 623191551);
	TextDrawSetShadow(Auction[7], 0);
	TextDrawSetOutline(Auction[7], 0);
	TextDrawBackgroundColor(Auction[7], 623191551);
	TextDrawFont(Auction[7], 2);
	TextDrawSetProportional(Auction[7], 1);

	Auction[8] = TextDrawCreate(408.166656, 349.774200, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Auction[8], 0.000000, 0.000000);
	TextDrawTextSize(Auction[8], 2.666625, 2.074080);
	TextDrawAlignment(Auction[8], 1);
	TextDrawColor(Auction[8], -36827905);
	TextDrawSetShadow(Auction[8], 0);
	TextDrawSetOutline(Auction[8], 0);
	TextDrawFont(Auction[8], 4);

	Auction[9] = TextDrawCreate(403.500000, 352.263061, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Auction[9], 0.000000, 0.000000);
	TextDrawTextSize(Auction[9], 2.666625, 2.074080);
	TextDrawAlignment(Auction[9], 1);
	TextDrawColor(Auction[9], -36827905);
	TextDrawSetShadow(Auction[9], 0);
	TextDrawSetOutline(Auction[9], 0);
	TextDrawFont(Auction[9], 4);

	Auction[10] = TextDrawCreate(233.166641, 416.974121, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Auction[10], 0.000000, 0.000000);
	TextDrawTextSize(Auction[10], 1.666625, 2.488895);
	TextDrawAlignment(Auction[10], 1);
	TextDrawColor(Auction[10], -36827905);
	TextDrawSetShadow(Auction[10], 0);
	TextDrawSetOutline(Auction[10], 0);
	TextDrawFont(Auction[10], 4);

	Auction[11] = TextDrawCreate(231.499954, 423.196319, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Auction[11], 0.000000, 0.000000);
	TextDrawTextSize(Auction[11], 1.666625, 2.488894);
	TextDrawAlignment(Auction[11], 1);
	TextDrawColor(Auction[11], -36827905);
	TextDrawSetShadow(Auction[11], 0);
	TextDrawSetOutline(Auction[11], 0);
	TextDrawFont(Auction[11], 4);

	Auction[12] = TextDrawCreate(346.500152, 364.481475, "box"); // Box element
	TextDrawLetterSize(Auction[12], 0.000000, 3.737245);
	TextDrawTextSize(Auction[12], 343.166595, -14.500000);
	TextDrawAlignment(Auction[12], 1);
	TextDrawColor(Auction[12], -36827905);
	TextDrawUseBox(Auction[12], true);
	TextDrawBoxColor(Auction[12], -36827905);
	TextDrawSetShadow(Auction[12], 0);
	TextDrawSetOutline(Auction[12], 0);
	TextDrawBackgroundColor(Auction[12], -36827905);
	TextDrawFont(Auction[12], 0);

	Auction[13] = TextDrawCreate(348.333496, 376.511108, "box"); // Box element
	TextDrawLetterSize(Auction[13], 0.000000, 3.737245);
	TextDrawTextSize(Auction[13], 344.999938, -14.500000);
	TextDrawAlignment(Auction[13], 1);
	TextDrawColor(Auction[13], -36827905);
	TextDrawUseBox(Auction[13], true);
	TextDrawBoxColor(Auction[13], -36827905);
	TextDrawSetShadow(Auction[13], 0);
	TextDrawSetOutline(Auction[13], 0);
	TextDrawBackgroundColor(Auction[13], -36827905);
	TextDrawFont(Auction[13], 0);

	Auction[14] = TextDrawCreate(210.333282, 373.407440, "LD_BEAT:left"); // box decorative <<<
	TextDrawLetterSize(Auction[14], 0.000000, 0.000000);
	TextDrawTextSize(Auction[14], 18.000032, 20.740753);
	TextDrawAlignment(Auction[14], 2);
	TextDrawColor(Auction[14], -1936945921);
	TextDrawUseBox(Auction[14], true);
	TextDrawBoxColor(Auction[14], 255);
	TextDrawSetShadow(Auction[14], 0);
	TextDrawSetOutline(Auction[14], 0);
	TextDrawFont(Auction[14], 4);
	TextDrawSetSelectable(Auction[14], true);

	Auction[15] = TextDrawCreate(409.333282, 373.407440, "LD_BEAT:right"); // box >>>
	TextDrawLetterSize(Auction[15], 0.000000, 0.000000);
	TextDrawTextSize(Auction[15], 18.000032, 20.740753);
	TextDrawAlignment(Auction[15], 2);
	TextDrawColor(Auction[15], -1936945921);
	TextDrawUseBox(Auction[15], true);
	TextDrawBoxColor(Auction[15], 255);
	TextDrawSetShadow(Auction[15], 0);
	TextDrawSetOutline(Auction[15], 0);
	TextDrawFont(Auction[15], 4);
	TextDrawSetSelectable(Auction[15], true);

	Auction[16] = TextDrawCreate(346.833251, 398.648071, "$"); // Text element
	TextDrawLetterSize(Auction[16], 0.216999, 1.492148);
	TextDrawAlignment(Auction[16], 2);
	TextDrawColor(Auction[16], -36827905);
	TextDrawSetShadow(Auction[16], 0);
	TextDrawSetOutline(Auction[16], 0);
	TextDrawBackgroundColor(Auction[16], 255);
	TextDrawFont(Auction[16], 2);
	TextDrawSetProportional(Auction[16], 1);

	Auction[17] = TextDrawCreate(345.166595, 360.070312, "$"); // Text element
	TextDrawLetterSize(Auction[17], 0.216999, 1.492148);
	TextDrawAlignment(Auction[17], 2);
	TextDrawColor(Auction[17], -36827905);
	TextDrawSetShadow(Auction[17], 0);
	TextDrawSetOutline(Auction[17], 0);
	TextDrawBackgroundColor(Auction[17], 255);
	TextDrawFont(Auction[17], 2);
	TextDrawSetProportional(Auction[17], 1);

	Auction[18] = TextDrawCreate(342.499969, 420.548126, "LD_SPAC:white"); // box make bet
	TextDrawLetterSize(Auction[18], 0.000000, 0.000000);
	TextDrawTextSize(Auction[18], 62.000000, 14.518524);
	TextDrawAlignment(Auction[18], 2);
	TextDrawColor(Auction[18], 623191551);
	TextDrawUseBox(Auction[18], true);
	TextDrawBoxColor(Auction[18], 255);
	TextDrawSetShadow(Auction[18], 0);
	TextDrawSetOutline(Auction[18], 0);
	TextDrawFont(Auction[18], 4);
	TextDrawSetSelectable(Auction[18], true);

	Auction[19] = TextDrawCreate(358.333251, 422.707305, "make bet"); // Text element
	TextDrawLetterSize(Auction[19], 0.156999, 0.994370);
	TextDrawAlignment(Auction[19], 1);
	TextDrawColor(Auction[19], -1);
	TextDrawSetShadow(Auction[19], 0);
	TextDrawSetOutline(Auction[19], 0);
	TextDrawBackgroundColor(Auction[19], 255);
	TextDrawFont(Auction[19], 2);
	TextDrawSetProportional(Auction[19], 1);

	Auction[20] = TextDrawCreate(234.499969, 420.548126, "LD_SPAC:white"); // box (click) exit
	TextDrawLetterSize(Auction[20], 0.000000, 0.000000);
	TextDrawTextSize(Auction[20], 62.000000, 14.518524);
	TextDrawAlignment(Auction[20], 2);
	TextDrawColor(Auction[20], 623191551);
	TextDrawSetShadow(Auction[20], 0);
	TextDrawSetOutline(Auction[20], 0);
	TextDrawBackgroundColor(Auction[20], -4119041);
	TextDrawFont(Auction[20], 4);
	TextDrawSetSelectable(Auction[20], true);

	Auction[21] = TextDrawCreate(258.833251, 422.707305, "exit"); // Text element
	TextDrawLetterSize(Auction[21], 0.156999, 0.994370);
	TextDrawAlignment(Auction[21], 1);
	TextDrawColor(Auction[21], -1);
	TextDrawSetShadow(Auction[21], 0);
	TextDrawSetOutline(Auction[21], 0);
	TextDrawBackgroundColor(Auction[21], 255);
	TextDrawFont(Auction[21], 2);
	TextDrawSetProportional(Auction[21], 1);

	ObjectBuy[0] = TextDrawCreate(266.166656, 405.177642, "ld_beat:chit"); // Texture element
	TextDrawLetterSize(ObjectBuy[0], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[0], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[0], 1);
	TextDrawColor(ObjectBuy[0], 336860415);
	TextDrawSetShadow(ObjectBuy[0], 0);
	TextDrawSetOutline(ObjectBuy[0], 0);
	TextDrawFont(ObjectBuy[0], 4);

	ObjectBuy[1] = TextDrawCreate(273.999908, 408.177612, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ObjectBuy[1], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[1], 80.666671, 11.614809);
	TextDrawAlignment(ObjectBuy[1], 1);
	TextDrawColor(ObjectBuy[1], 336860415);
	TextDrawSetShadow(ObjectBuy[1], 0);
	TextDrawSetOutline(ObjectBuy[1], 0);
	TextDrawFont(ObjectBuy[1], 4);

	ObjectBuy[2] = TextDrawCreate(347.166656, 405.177612, "ld_beat:chit"); // Texture element
	TextDrawLetterSize(ObjectBuy[2], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[2], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[2], 1);
	TextDrawColor(ObjectBuy[2], 336860415);
	TextDrawSetShadow(ObjectBuy[2], 0);
	TextDrawSetOutline(ObjectBuy[2], 0);
	TextDrawFont(ObjectBuy[2], 4);

	ObjectBuy[3] = TextDrawCreate(276.833404, 408.722167, "<<"); // box <<<
	TextDrawLetterSize(ObjectBuy[3], 0.176991, 1.114662);
	TextDrawTextSize(ObjectBuy[3], 12.000000, 19.118513);
	TextDrawAlignment(ObjectBuy[3], 2);
	TextDrawColor(ObjectBuy[3], -36827905);
	TextDrawSetShadow(ObjectBuy[3], 0);
	TextDrawSetOutline(ObjectBuy[3], 0);
	TextDrawBackgroundColor(ObjectBuy[3], 51);
	TextDrawFont(ObjectBuy[3], 3);
	TextDrawSetProportional(ObjectBuy[3], 1);

	ObjectBuy[4] = TextDrawCreate(351.166687, 408.307312, ">>"); // box >>
	TextDrawLetterSize(ObjectBuy[4], 0.176991, 1.114662);
	TextDrawTextSize(ObjectBuy[4], 12.000000, 19.118513);
	TextDrawAlignment(ObjectBuy[4], 2);
	TextDrawColor(ObjectBuy[4], -36827905);
	TextDrawSetShadow(ObjectBuy[4], 0);
	TextDrawSetOutline(ObjectBuy[4], 0);
	TextDrawBackgroundColor(ObjectBuy[4], 51);
	TextDrawFont(ObjectBuy[4], 3);
	TextDrawSetProportional(ObjectBuy[4], 1);

	ObjectBuy[5] = TextDrawCreate(234.166641, 388.585052, "ld_beat:chit"); // box exit
	TextDrawLetterSize(ObjectBuy[5], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[5], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[5], 1);
	TextDrawColor(ObjectBuy[5], -483052033);
	TextDrawUseBox(ObjectBuy[5], true);
	TextDrawBoxColor(ObjectBuy[5], 255);
	TextDrawSetShadow(ObjectBuy[5], 0);
	TextDrawSetOutline(ObjectBuy[5], 0);
	TextDrawFont(ObjectBuy[5], 4);
	TextDrawSetSelectable(ObjectBuy[5], true);

	ObjectBuy[6] = TextDrawCreate(249.166625, 418.451812, "ld_beat:chit"); // Texture element
	TextDrawLetterSize(ObjectBuy[6], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[6], 26.333330, 26.962965);
	TextDrawAlignment(ObjectBuy[6], 1);
	TextDrawColor(ObjectBuy[6], -36827905);
	TextDrawSetShadow(ObjectBuy[6], 0);
	TextDrawSetOutline(ObjectBuy[6], 0);
	TextDrawFont(ObjectBuy[6], 4);

	ObjectBuy[7] = TextDrawCreate(262.666687, 423.111022, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(ObjectBuy[7], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[7], 102.666702, 17.837034);
	TextDrawAlignment(ObjectBuy[7], 1);
	TextDrawColor(ObjectBuy[7], -36827905);
	TextDrawSetShadow(ObjectBuy[7], 0);
	TextDrawSetOutline(ObjectBuy[7], 0);
	TextDrawFont(ObjectBuy[7], 4);

	ObjectBuy[8] = TextDrawCreate(353.166625, 418.451812, "ld_beat:chit"); // Texture element
	TextDrawLetterSize(ObjectBuy[8], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[8], 24.999994, 26.962965);
	TextDrawAlignment(ObjectBuy[8], 1);
	TextDrawColor(ObjectBuy[8], -36827905);
	TextDrawSetShadow(ObjectBuy[8], 0);
	TextDrawSetOutline(ObjectBuy[8], 0);
	TextDrawFont(ObjectBuy[8], 4);

	ObjectBuy[9] = TextDrawCreate(259.666625, 388.585052, "ld_beat:chit"); // box exit
	TextDrawLetterSize(ObjectBuy[9], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[9], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[9], 1);
	TextDrawColor(ObjectBuy[9], -483052033);
	TextDrawUseBox(ObjectBuy[9], true);
	TextDrawBoxColor(ObjectBuy[9], 255);
	TextDrawSetShadow(ObjectBuy[9], 0);
	TextDrawSetOutline(ObjectBuy[9], 0);
	TextDrawFont(ObjectBuy[9], 4);
	TextDrawSetSelectable(ObjectBuy[9], true);

	ObjectBuy[10] = TextDrawCreate(355.666625, 388.585052, "ld_beat:chit"); // box buy
	TextDrawLetterSize(ObjectBuy[10], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[10], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[10], 1);
	TextDrawColor(ObjectBuy[10], 1640450303);
	TextDrawUseBox(ObjectBuy[10], true);
	TextDrawBoxColor(ObjectBuy[10], 255);
	TextDrawSetShadow(ObjectBuy[10], 0);
	TextDrawSetOutline(ObjectBuy[10], 0);
	TextDrawFont(ObjectBuy[10], 4);
	TextDrawSetSelectable(ObjectBuy[10], true);

	ObjectBuy[11] = TextDrawCreate(382.166625, 388.585052, "ld_beat:chit"); // box buy
	TextDrawLetterSize(ObjectBuy[11], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[11], 14.333327, 17.422225);
	TextDrawAlignment(ObjectBuy[11], 1);
	TextDrawColor(ObjectBuy[11], 1640450303);
	TextDrawUseBox(ObjectBuy[11], true);
	TextDrawBoxColor(ObjectBuy[11], 255);
	TextDrawSetShadow(ObjectBuy[11], 0);
	TextDrawSetOutline(ObjectBuy[11], 0);
	TextDrawFont(ObjectBuy[11], 4);
	TextDrawSetSelectable(ObjectBuy[11], true);

	ObjectBuy[12] = TextDrawCreate(265.000061, 426.144378, "<<<"); // box <<<
	TextDrawLetterSize(ObjectBuy[12], 0.200330, 1.313773);
	TextDrawTextSize(ObjectBuy[12], 10.000000, 27.000000);
	TextDrawAlignment(ObjectBuy[12], 2);
	TextDrawColor(ObjectBuy[12], 255);
	TextDrawUseBox(ObjectBuy[12], true);
	TextDrawBoxColor(ObjectBuy[12], -650166528);
	TextDrawSetShadow(ObjectBuy[12], 0);
	TextDrawSetOutline(ObjectBuy[12], 0);
	TextDrawBackgroundColor(ObjectBuy[12], 51);
	TextDrawFont(ObjectBuy[12], 3);
	TextDrawSetProportional(ObjectBuy[12], 1);
	TextDrawSetSelectable(ObjectBuy[12], true);

	ObjectBuy[13] = TextDrawCreate(363.500061, 426.144378, ">>>"); // box >>>
	TextDrawLetterSize(ObjectBuy[13], 0.200330, 1.313773);
	TextDrawTextSize(ObjectBuy[13], 10.000000, 27.000000);
	TextDrawAlignment(ObjectBuy[13], 2);
	TextDrawColor(ObjectBuy[13], 255);
	TextDrawUseBox(ObjectBuy[13], true);
	TextDrawBoxColor(ObjectBuy[13], -650166528);
	TextDrawSetShadow(ObjectBuy[13], 0);
	TextDrawSetOutline(ObjectBuy[13], 0);
	TextDrawBackgroundColor(ObjectBuy[13], 51);
	TextDrawFont(ObjectBuy[13], 3);
	TextDrawSetProportional(ObjectBuy[13], 1);
	TextDrawSetSelectable(ObjectBuy[13], true);

	ObjectBuy[14] = TextDrawCreate(241.666687, 391.340820, "LD_SPAC:white"); // box exit
	TextDrawLetterSize(ObjectBuy[14], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[14], 26.000000, 11.614787);
	TextDrawAlignment(ObjectBuy[14], 1);
	TextDrawColor(ObjectBuy[14], -483052033);
	TextDrawUseBox(ObjectBuy[14], true);
	TextDrawBoxColor(ObjectBuy[14], 255);
	TextDrawSetShadow(ObjectBuy[14], 0);
	TextDrawSetOutline(ObjectBuy[14], 0);
	TextDrawFont(ObjectBuy[14], 4);
	TextDrawSetSelectable(ObjectBuy[14], true);

	ObjectBuy[15] = TextDrawCreate(363.666595, 391.340759, "LD_SPAC:white"); // box buy
	TextDrawLetterSize(ObjectBuy[15], 0.000000, 0.000000);
	TextDrawTextSize(ObjectBuy[15], 26.000000, 11.614787);
	TextDrawAlignment(ObjectBuy[15], 1);
	TextDrawColor(ObjectBuy[15], 1640450303);
	TextDrawUseBox(ObjectBuy[15], true);
	TextDrawBoxColor(ObjectBuy[15], 255);
	TextDrawSetShadow(ObjectBuy[15], 0);
	TextDrawSetOutline(ObjectBuy[15], 0);
	TextDrawFont(ObjectBuy[15], 4);
	TextDrawSetSelectable(ObjectBuy[15], true);

	ObjectBuy[16] = TextDrawCreate(254.333358, 391.055450, "exit"); // object name
	TextDrawLetterSize(ObjectBuy[16], 0.182327, 1.214215);
	TextDrawTextSize(ObjectBuy[16], 10.000000, 41.000000);
	TextDrawAlignment(ObjectBuy[16], 2);
	TextDrawColor(ObjectBuy[16], -1);
	TextDrawSetShadow(ObjectBuy[16], 0);
	TextDrawSetOutline(ObjectBuy[16], 0);
	TextDrawBackgroundColor(ObjectBuy[16], 51);
	TextDrawFont(ObjectBuy[16], 2);
	TextDrawSetProportional(ObjectBuy[16], 1);

	ObjectBuy[17] = TextDrawCreate(376.666656, 391.640625, "select"); // object name
	TextDrawLetterSize(ObjectBuy[17], 0.154991, 1.102216);
	TextDrawTextSize(ObjectBuy[17], 10.000000, 41.000000);
	TextDrawAlignment(ObjectBuy[17], 2);
	TextDrawColor(ObjectBuy[17], -1);
	TextDrawSetShadow(ObjectBuy[17], 0);
	TextDrawSetOutline(ObjectBuy[17], 0);
	TextDrawBackgroundColor(ObjectBuy[17], 51);
	TextDrawFont(ObjectBuy[17], 2);
	TextDrawSetProportional(ObjectBuy[17], 1);

    Casino[0] = TextDrawCreate(11.666666, 136.474060, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[0], 0.000000, 0.000000);
	TextDrawTextSize(Casino[0], 199.333343, 120.711120);
	TextDrawAlignment(Casino[0], 1);
	TextDrawColor(Casino[0], 0x252525FF);
	TextDrawSetShadow(Casino[0], 0);
	TextDrawSetOutline(Casino[0], 0);
	TextDrawFont(Casino[0], 4);

	Casino[1] = TextDrawCreate(12.500000, 137.718490, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[1], 0.000000, 0.000000);
	TextDrawTextSize(Casino[1], 197.333343, 118.222229);
	TextDrawAlignment(Casino[1], 1);
	TextDrawColor(Casino[1], -36827905);
	TextDrawSetShadow(Casino[1], 0);
	TextDrawSetOutline(Casino[1], 0);
	TextDrawFont(Casino[1], 4);

	Casino[2] = TextDrawCreate(13.333333, 138.462966, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[2], 0.000000, 0.000000);
	TextDrawTextSize(Casino[2], 196.000015, 116.562973);
	TextDrawAlignment(Casino[2], 1);
	TextDrawColor(Casino[2], 0x252525FF);
	TextDrawSetShadow(Casino[2], 0);
	TextDrawSetOutline(Casino[2], 0);
	TextDrawFont(Casino[2], 4);

	Casino[3] = TextDrawCreate(13.833333, 139.270370, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[3], 0.000000, 0.000000);
	TextDrawTextSize(Casino[3], 194.666671, 15.348137);
	TextDrawAlignment(Casino[3], 1);
	TextDrawColor(Casino[3], -36827905);
	TextDrawSetShadow(Casino[3], 0);
	TextDrawSetOutline(Casino[3], 0);
	TextDrawFont(Casino[3], 4);

	Casino[4] = TextDrawCreate(19.833332, 155.270370, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[4], 0.000000, 0.000000);
	TextDrawTextSize(Casino[4], 190.000045, 1.244436);
	TextDrawAlignment(Casino[4], 1);
	TextDrawColor(Casino[4], -36827905);
	TextDrawSetShadow(Casino[4], 0);
	TextDrawSetOutline(Casino[4], 0);
	TextDrawFont(Casino[4], 4);

	Casino[5] = TextDrawCreate(12.499996, 157.355545, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[5], 0.000000, 0.000000);
	TextDrawTextSize(Casino[5], 179.999954, 1.244435);
	TextDrawAlignment(Casino[5], 1);
	TextDrawColor(Casino[5], -36827905);
	TextDrawSetShadow(Casino[5], 0);
	TextDrawSetOutline(Casino[5], 0);
	TextDrawFont(Casino[5], 4);

	Casino[6] = TextDrawCreate(59.333354, 141.451873, "game_table_in_casino"); // Text element
	TextDrawLetterSize(Casino[6], 0.218999, 1.222518);
	TextDrawAlignment(Casino[6], 1);
	TextDrawColor(Casino[6], 255);
	TextDrawUseBox(Casino[6], true);
	TextDrawBoxColor(Casino[6], 0);
	TextDrawSetShadow(Casino[6], 0);
	TextDrawSetOutline(Casino[6], 1);
	TextDrawBackgroundColor(Casino[6], -256);
	TextDrawFont(Casino[6], 2);
	TextDrawSetProportional(Casino[6], 1);

	Casino[7] = TextDrawCreate(27.166666, 172.562957, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[7], 0.000000, 0.000000);
	TextDrawTextSize(Casino[7], 166.666656, 1.659271);
	TextDrawAlignment(Casino[7], 1);
	TextDrawColor(Casino[7], -1);
	TextDrawSetShadow(Casino[7], 0);
	TextDrawSetOutline(Casino[7], 0);
	TextDrawFont(Casino[7], 4);

	Casino[8] = TextDrawCreate(25.000003, 171.733322, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Casino[8], 0.000000, 0.000000);
	TextDrawTextSize(Casino[8], 2.999994, 2.903712);
	TextDrawAlignment(Casino[8], 1);
	TextDrawColor(Casino[8], -1);
	TextDrawSetShadow(Casino[8], 0);
	TextDrawSetOutline(Casino[8], 0);
	TextDrawFont(Casino[8], 4);

	Casino[9] = TextDrawCreate(192.333328, 171.733306, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Casino[9], 0.000000, 0.000000);
	TextDrawTextSize(Casino[9], 2.999994, 2.903712);
	TextDrawAlignment(Casino[9], 1);
	TextDrawColor(Casino[9], -1);
	TextDrawSetShadow(Casino[9], 0);
	TextDrawSetOutline(Casino[9], 0);
	TextDrawFont(Casino[9], 4);

	Casino[10] = TextDrawCreate(13.000000, 185.474075, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Casino[10], 0.000000, 0.000000);
	TextDrawTextSize(Casino[10], 115.000000, 14.103706);
	TextDrawAlignment(Casino[10], 1);
	TextDrawColor(Casino[10], -36827905);
	TextDrawSetShadow(Casino[10], 0);
	TextDrawSetOutline(Casino[10], 0);
	TextDrawFont(Casino[10], 4);

	Casino[11] = TextDrawCreate(117.999992, 182.103713, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Casino[11], 0.000000, 0.000000);
	TextDrawTextSize(Casino[11], 18.666669, 21.155569);
	TextDrawAlignment(Casino[11], 1);
	TextDrawColor(Casino[11], -36827905);
	TextDrawSetShadow(Casino[11], 0);
	TextDrawSetOutline(Casino[11], 0);
	TextDrawFont(Casino[11], 4);




	Casino[12] = TextDrawCreate(203.000061, 240.433441, "box"); // box exit
	TextDrawLetterSize(Casino[12], 0.000000, 1.050410);
	TextDrawTextSize(Casino[12], 137.000000, 15.000000);
	TextDrawAlignment(Casino[12], 1);
	TextDrawColor(Casino[12], -36827905);
	TextDrawUseBox(Casino[12], true);
	TextDrawBoxColor(Casino[12], -36827905);
	TextDrawSetShadow(Casino[12], 0);
	TextDrawSetOutline(Casino[12], 0);
	TextDrawBackgroundColor(Casino[12], -36827905);
	TextDrawFont(Casino[12], 0);
	TextDrawSetProportional(Casino[12], 1);
	TextDrawSetSelectable(Casino[12], true);

	Casino[13] = TextDrawCreate(203.000061, 225.433441, "box"); // box play
	TextDrawLetterSize(Casino[13], 0.000000, 1.050410);
	TextDrawTextSize(Casino[13], 137.000000, 15.000000);
	TextDrawAlignment(Casino[13], 1);
	TextDrawColor(Casino[13], 0x252525FF);
	TextDrawUseBox(Casino[13], true);
	TextDrawBoxColor(Casino[13], -36827905);
	TextDrawSetShadow(Casino[13], 0);
	TextDrawSetOutline(Casino[13], 0);
	TextDrawBackgroundColor(Casino[13], -36827905);
	TextDrawFont(Casino[13], 0);
	TextDrawSetProportional(Casino[13], 1);
	TextDrawSetSelectable(Casino[13], true);

	Casino[14] = TextDrawCreate(203.000061, 210.433441, "box"); // box set bet
	TextDrawLetterSize(Casino[14], 0.000000, 1.050410);
	TextDrawTextSize(Casino[14], 137.000000, 15.000000);
	TextDrawAlignment(Casino[14], 1);
	TextDrawColor(Casino[14], 714338303);
	TextDrawUseBox(Casino[14], true);
	TextDrawBoxColor(Casino[14], -36827905);
	TextDrawSetShadow(Casino[14], 0);
	TextDrawSetOutline(Casino[14], 0);
	TextDrawBackgroundColor(Casino[14], -1);
	TextDrawFont(Casino[14], 0);
	TextDrawSetProportional(Casino[14], 1);
	TextDrawSetSelectable(Casino[14], true);

	Casino[15] = TextDrawCreate(205.166656, 196.622268, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Casino[15], 0.000000, 0.000000);
	TextDrawTextSize(Casino[15], 1.999993, 3.318526);
	TextDrawAlignment(Casino[15], 1);
	TextDrawColor(Casino[15], -36827905);
	TextDrawSetShadow(Casino[15], 0);
	TextDrawSetOutline(Casino[15], 0);
	TextDrawFont(Casino[15], 4);


    Casino[16] = TextDrawCreate( 205.666671, 198.540771, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize( Casino[16], 0.000000, 0.000000);
	TextDrawTextSize( Casino[16], 1.333323, 57.244445);
	TextDrawAlignment( Casino[16], 1);
	TextDrawColor( Casino[16], -36827905);
	TextDrawSetShadow( Casino[16], 0);
	TextDrawSetOutline( Casino[16], 0);
	TextDrawFont( Casino[16], 4);


/*	Casino[16] = TextDrawCreate( 155.166702, 210.033309, "set_bet"); // box bet of game
	TextDrawLetterSize( Casino[16], 0.185666, 1.098074);
	TextDrawAlignment( Casino[16], 1);
	TextDrawColor( Casino[16], 255);
	TextDrawSetShadow( Casino[16], 0);
	TextDrawSetOutline( Casino[16], 0);
	TextDrawBackgroundColor( Casino[16], 255);
	TextDrawFont( Casino[16], 2);
	TextDrawSetProportional( Casino[16], 1);*/

	Casino[17] = TextDrawCreate( 160.500045, 225.051818, "play"); // box bet of game
	TextDrawLetterSize( Casino[17], 0.185665, 1.098073);
	TextDrawAlignment( Casino[17], 1);
	TextDrawColor( Casino[17], 255);
	TextDrawSetShadow( Casino[17], 0);
	TextDrawSetOutline( Casino[17], 0);
	TextDrawBackgroundColor( Casino[17], 255);
	TextDrawFont( Casino[17], 2);
	TextDrawSetProportional( Casino[17], 1);

	Casino[18] = TextDrawCreate( 163.000045, 239.974090, "exit"); // box bet of game
	TextDrawLetterSize( Casino[18], 0.185666, 1.098074);
	TextDrawAlignment( Casino[18], 1);
	TextDrawColor( Casino[18], 255);
	TextDrawSetShadow( Casino[18], 0);
	TextDrawSetOutline( Casino[18], 0);
	TextDrawBackgroundColor( Casino[18], 255);
	TextDrawFont( Casino[18], 2);
	TextDrawSetProportional( Casino[18], 1);

	Casino[19] = TextDrawCreate( 202.333343, 174.066665, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize( Casino[19], 0.000000, 0.000000);
	TextDrawTextSize( Casino[19], 1.333323, 80.888885);
	TextDrawAlignment( Casino[19], 1);
	TextDrawColor( Casino[19], -36827905);
	TextDrawSetShadow( Casino[19], 0);
	TextDrawSetOutline( Casino[19], 0);
	TextDrawFont( Casino[19], 4);

	Casino[20] = TextDrawCreate( 201.833312, 172.148147, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize( Casino[20], 0.000000, 0.000000);
	TextDrawTextSize( Casino[20], 1.999993, 3.318526);
	TextDrawAlignment( Casino[20], 1);
	TextDrawColor( Casino[20], -36827905);
	TextDrawSetShadow( Casino[20], 0);
	TextDrawSetOutline( Casino[20], 0);
	TextDrawFont( Casino[20], 4);

	

	Speedometr[0] = TextDrawCreate(510.000000, 376.640808, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[0], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[0], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[0], 1);
	TextDrawColor(Speedometr[0], -36827905);
	TextDrawSetShadow(Speedometr[0], 0);
	TextDrawSetOutline(Speedometr[0], 0);
	TextDrawFont(Speedometr[0], 4);

	Speedometr[1] = TextDrawCreate(517.500000, 379.544433, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[1], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[1], 108.666679, 10.785176);
	TextDrawAlignment(Speedometr[1], 1);
	TextDrawColor(Speedometr[1], 0x252525FF);
	TextDrawSetShadow(Speedometr[1], 0);
	TextDrawSetOutline(Speedometr[1], 0);
	TextDrawFont(Speedometr[1], 4);

	Speedometr[2] = TextDrawCreate(619.500000, 376.640808, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[2], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[2], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[2], 1);
	TextDrawColor(Speedometr[2], 0x252525FF);
	TextDrawSetShadow(Speedometr[2], 0);
	TextDrawSetOutline(Speedometr[2], 0);
	TextDrawFont(Speedometr[2], 4);

	Speedometr[3] = TextDrawCreate(512.166687, 385.766601, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[3], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[3], 118.333343, 49.362968);
	TextDrawAlignment(Speedometr[3], 1);
	TextDrawColor(Speedometr[3], 0x252525FF);
	TextDrawSetShadow(Speedometr[3], 0);
	TextDrawSetOutline(Speedometr[3], 0);
	TextDrawFont(Speedometr[3], 4);

	Speedometr[4] = TextDrawCreate(619.500000, 426.140808, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[4], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[4], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[4], 1);
	TextDrawColor(Speedometr[4], 0x252525FF);
	TextDrawSetShadow(Speedometr[4], 0);
	TextDrawSetOutline(Speedometr[4], 0);
	TextDrawFont(Speedometr[4], 4);

	Speedometr[5] = TextDrawCreate(510.000000, 426.140808, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[5], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[5], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[5], 1);
	TextDrawColor(Speedometr[5], -36827905);
	TextDrawSetShadow(Speedometr[5], 0);
	TextDrawSetOutline(Speedometr[5], 0);
	TextDrawFont(Speedometr[5], 4);

	Speedometr[6] = TextDrawCreate(511.333251, 376.811157, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[6], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[6], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[6], 1);
	TextDrawColor(Speedometr[6], 0x252525FF);
	TextDrawSetShadow(Speedometr[6], 0);
	TextDrawSetOutline(Speedometr[6], 0);
	TextDrawFont(Speedometr[6], 4);

	Speedometr[7] = TextDrawCreate(511.333251, 426.174072, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[7], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[7], 13.333328, 16.177734);
	TextDrawAlignment(Speedometr[7], 1);
	TextDrawColor(Speedometr[7], 0x252525FF);
	TextDrawSetShadow(Speedometr[7], 0);
	TextDrawSetOutline(Speedometr[7], 0);
	TextDrawFont(Speedometr[7], 4);

	Speedometr[8] = TextDrawCreate(512.166748, 384.936828, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[8], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[8], 1.333343, 48.118515);
	TextDrawAlignment(Speedometr[8], 1);
	TextDrawColor(Speedometr[8], -36827905);
	TextDrawSetShadow(Speedometr[8], 0);
	TextDrawSetOutline(Speedometr[8], 0);
	TextDrawFont(Speedometr[8], 4);

	Speedometr[9] = TextDrawCreate(517.000061, 434.544250, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[9], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[9], 110.000053, 4.977766);
	TextDrawAlignment(Speedometr[9], 1);
	TextDrawColor(Speedometr[9], 0x252525FF);
	TextDrawSetShadow(Speedometr[9], 0);
	TextDrawSetOutline(Speedometr[9], 0);
	TextDrawFont(Speedometr[9], 4);

	Speedometr[10] = TextDrawCreate(513.500061, 427.248199, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[10], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[10], 111.333351, 6.637042);
	TextDrawAlignment(Speedometr[10], 1);
	TextDrawColor(Speedometr[10], 0x252525FF);
	TextDrawSetShadow(Speedometr[10], 0);
	TextDrawSetOutline(Speedometr[10], 0);
	TextDrawFont(Speedometr[10], 4);

	Speedometr[11] = TextDrawCreate(559.166870, 385.214874, "km/h"); // box current speed (pl)
	TextDrawLetterSize(Speedometr[11], 0.321662, 1.711997);
	TextDrawAlignment(Speedometr[11], 2);
	TextDrawColor(Speedometr[11], -1936945921);
	TextDrawUseBox(Speedometr[11], true);
	TextDrawBoxColor(Speedometr[11], 0);
	TextDrawSetShadow(Speedometr[11], 0);
	TextDrawSetOutline(Speedometr[11], 0);
	TextDrawBackgroundColor(Speedometr[11], 51);
	TextDrawFont(Speedometr[11], 1);
	TextDrawSetProportional(Speedometr[11], 1);

	Speedometr[12] = TextDrawCreate(517.000000, 403.455505, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[12], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[12], 109.999969, 1.244446);
	TextDrawAlignment(Speedometr[12], 1);
	TextDrawColor(Speedometr[12], -1936945921);
	TextDrawSetShadow(Speedometr[12], 0);
	TextDrawSetOutline(Speedometr[12], 0);
	TextDrawFont(Speedometr[12], 4);

	Speedometr[13] = TextDrawCreate(514.333312, 402.785125, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[13], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[13], 3.666666, 2.488893);
	TextDrawAlignment(Speedometr[13], 1);
	TextDrawColor(Speedometr[13], -1936945921);
	TextDrawSetShadow(Speedometr[13], 0);
	TextDrawSetOutline(Speedometr[13], 0);
	TextDrawFont(Speedometr[13], 4);

	Speedometr[14] = TextDrawCreate(518.333374, 406.370544, "engine~n~doors~n~light"); // Text element
	TextDrawLetterSize(Speedometr[14], 0.165326, 1.135403);
	TextDrawAlignment(Speedometr[14], 1);
	TextDrawColor(Speedometr[14], -1);
	TextDrawSetShadow(Speedometr[14], 0);
	TextDrawSetOutline(Speedometr[14], 0);
	TextDrawBackgroundColor(Speedometr[14], 51);
	TextDrawFont(Speedometr[14], 2);
	TextDrawSetProportional(Speedometr[14], 1);

	Speedometr[15] = TextDrawCreate(625.999877, 402.785186, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[15], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[15], 3.666666, 2.488893);
	TextDrawAlignment(Speedometr[15], 1);
	TextDrawColor(Speedometr[15], -1936945921);
	TextDrawSetShadow(Speedometr[15], 0);
	TextDrawSetOutline(Speedometr[15], 0);
	TextDrawFont(Speedometr[15], 4);

	Speedometr[16] = TextDrawCreate(577.333251, 382.777618, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[16], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[16], 0.999966, 21.570354);
	TextDrawAlignment(Speedometr[16], 1);
	TextDrawColor(Speedometr[16], -1936945921);
	TextDrawSetShadow(Speedometr[16], 0);
	TextDrawSetOutline(Speedometr[16], 0);
	TextDrawFont(Speedometr[16], 4);

	Speedometr[17] = TextDrawCreate(576.833190, 380.629608, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Speedometr[17], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[17], 1.666664, 2.488893);
	TextDrawAlignment(Speedometr[17], 1);
	TextDrawColor(Speedometr[17], -1936945921);
	TextDrawSetShadow(Speedometr[17], 0);
	TextDrawSetOutline(Speedometr[17], 0);
	TextDrawFont(Speedometr[17], 4);

	Speedometr[18] = TextDrawCreate(586.000183, 384.948150, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[18], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[18], 2.999998, 14.518524);
	TextDrawAlignment(Speedometr[18], 1);
	TextDrawColor(Speedometr[18], -382783489);
	TextDrawSetShadow(Speedometr[18], 0);
	TextDrawSetOutline(Speedometr[18], 0);
	TextDrawFont(Speedometr[18], 4);

	Speedometr[19] = TextDrawCreate(582.166748, 390.011199, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[19], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[19], 10.333331, 3.733338);
	TextDrawAlignment(Speedometr[19], 1);
	TextDrawColor(Speedometr[19], -382783489);
	TextDrawSetShadow(Speedometr[19], 0);
	TextDrawSetOutline(Speedometr[19], 0);
	TextDrawFont(Speedometr[19], 4);

	Speedometr[20] = TextDrawCreate(561.166687, 408.422210, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[20], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[20], 13.666625, 26.962982);
	TextDrawAlignment(Speedometr[20], 1);
	TextDrawColor(Speedometr[20], -1);
	TextDrawSetShadow(Speedometr[20], 0);
	TextDrawSetOutline(Speedometr[20], 0);
	TextDrawFont(Speedometr[20], 4);

	Speedometr[21] = TextDrawCreate(559.666687, 433.725952, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[21], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[21], 16.999954, 2.488903);
	TextDrawAlignment(Speedometr[21], 1);
	TextDrawColor(Speedometr[21], -1);
	TextDrawSetShadow(Speedometr[21], 0);
	TextDrawSetOutline(Speedometr[21], 0);
	TextDrawFont(Speedometr[21], 4);

	Speedometr[22] = TextDrawCreate(563.000183, 410.581481, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[22], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[22], 10.666621, 9.540758);
	TextDrawAlignment(Speedometr[22], 1);
	TextDrawColor(Speedometr[22], 255);
	TextDrawSetShadow(Speedometr[22], 0);
	TextDrawSetOutline(Speedometr[22], 0);
	TextDrawFont(Speedometr[22], 4);

	Speedometr[23] = TextDrawCreate(573.500000, 420.951904, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[23], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[23], 2.666620, 2.488903);
	TextDrawAlignment(Speedometr[23], 1);
	TextDrawColor(Speedometr[23], -1);
	TextDrawSetShadow(Speedometr[23], 0);
	TextDrawSetOutline(Speedometr[23], 0);
	TextDrawFont(Speedometr[23], 4);

	Speedometr[24] = TextDrawCreate(576.166748, 429.663024, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[24], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[24], 3.666620, 2.074090);
	TextDrawAlignment(Speedometr[24], 1);
	TextDrawColor(Speedometr[24], -1);
	TextDrawSetShadow(Speedometr[24], 0);
	TextDrawSetOutline(Speedometr[24], 0);
	TextDrawFont(Speedometr[24], 4);

	Speedometr[25] = TextDrawCreate(579.166748, 412.803710, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[25], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[25], 1.666620, 18.666685);
	TextDrawAlignment(Speedometr[25], 1);
	TextDrawColor(Speedometr[25], -1);
	TextDrawSetShadow(Speedometr[25], 0);
	TextDrawSetOutline(Speedometr[25], 0);
	TextDrawFont(Speedometr[25], 4);

	Speedometr[26] = TextDrawCreate(574.166809, 411.559204, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[26], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[26], 6.666621, 2.074093);
	TextDrawAlignment(Speedometr[26], 1);
	TextDrawColor(Speedometr[26], -1);
	TextDrawSetShadow(Speedometr[26], 0);
	TextDrawSetOutline(Speedometr[26], 0);
	TextDrawFont(Speedometr[26], 4);

	Speedometr[27] = TextDrawCreate(574.833496, 409.814788, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[27], 0.000000, 0.000000);
	TextDrawTextSize(Speedometr[27], 0.999952, 6.637053);
	TextDrawAlignment(Speedometr[27], 1);
	TextDrawColor(Speedometr[27], -1);
	TextDrawSetShadow(Speedometr[27], 0);
	TextDrawSetOutline(Speedometr[27], 0);
	TextDrawFont(Speedometr[27], 4);
	
	Speedometr[28] = TextDrawCreate( 576.166687, 420.951904, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Speedometr[28], 0.000000, 0.000000);
	TextDrawTextSize( Speedometr[28], 1.666620, 9.955574);
	TextDrawAlignment( Speedometr[28], 1);
	TextDrawColor( Speedometr[28], -1);
	TextDrawSetShadow( Speedometr[28], 0);
	TextDrawSetOutline( Speedometr[28], 0);
	TextDrawFont( Speedometr[28], 4);
	
	Inventory1[0] = TextDrawCreate(321.999877-202.666717, 111.240676, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[0], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[0], 201.666717, 288.296905);
	TextDrawAlignment(Inventory1[0], 1);
	TextDrawColor(Inventory1[0], 336860415);
	TextDrawSetShadow(Inventory1[0], 0);
	TextDrawSetOutline(Inventory1[0], 0);
	TextDrawFont(Inventory1[0], 4);

	Inventory1[1] = TextDrawCreate(322.000061-202.666717, 131.133285, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[1], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[1], 201.666702, 1.244541);
	TextDrawAlignment(Inventory1[1], 1);
	TextDrawColor(Inventory1[1], -37548801);
	TextDrawSetShadow(Inventory1[1], 0);
	TextDrawSetOutline(Inventory1[1], 0);
	TextDrawFont(Inventory1[1], 4);

	Inventory1[2] = TextDrawCreate(322.000061-202.666717, 398.688903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[2], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[2], 201.666702, 1.244541);
	TextDrawAlignment(Inventory1[2], 1);
	TextDrawColor(Inventory1[2], -37548801);
	TextDrawSetShadow(Inventory1[2], 0);
	TextDrawSetOutline(Inventory1[2], 0);
	TextDrawFont(Inventory1[2], 4);

	Inventory1[3] = TextDrawCreate(450.999908-202.666717, 111.222129, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[3], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[3], 72.666725, 20.326021);
	TextDrawAlignment(Inventory1[3], 1);
	TextDrawColor(Inventory1[3], -37548801);
	TextDrawSetShadow(Inventory1[3], 0);
	TextDrawSetOutline(Inventory1[3], 0);
	TextDrawFont(Inventory1[3], 4);

	Inventory1[4] = TextDrawCreate(467.166748-202.666717, 116.562973, "HOUSE"); // Text element
	TextDrawLetterSize(Inventory1[4], 0.182332, 1.077334);
	TextDrawAlignment(Inventory1[4], 1);
	TextDrawColor(Inventory1[4], 336860415);
	TextDrawSetShadow(Inventory1[4], 0);
	TextDrawSetOutline(Inventory1[4], 0);
	TextDrawBackgroundColor(Inventory1[4], 255);
	TextDrawFont(Inventory1[4], 2);
	TextDrawSetProportional(Inventory1[4], 1);

	Inventory1[5] = TextDrawCreate(344.666717-202.666717, 394.511108, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[5], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[5], 56.666645, 1.659229);
	TextDrawAlignment(Inventory1[5], 1);
	TextDrawColor(Inventory1[5], -37548801);
	TextDrawSetShadow(Inventory1[5], 0);
	TextDrawSetOutline(Inventory1[5], 0);
	TextDrawFont(Inventory1[5], 4);

	Inventory1[6] = TextDrawCreate(444.666717-202.666717, 394.840759, "LD_SPAC:white"); // box buttom next page of the Inventory1
	TextDrawLetterSize(Inventory1[6], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[6], 56.333312, 1.659229);
	TextDrawAlignment(Inventory1[6], 1);
	TextDrawColor(Inventory1[6], -37548801);
	TextDrawSetShadow(Inventory1[6], 0);
	TextDrawSetOutline(Inventory1[6], 0);
	TextDrawFont(Inventory1[6], 4);

	Inventory1[7] = TextDrawCreate(442.332946-202.666717, 394.266540, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory1[7], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[7], 2.999958, 2.488888);
	TextDrawAlignment(Inventory1[7], 1);
	TextDrawColor(Inventory1[7], -37548801);
	TextDrawSetShadow(Inventory1[7], 0);
	TextDrawSetOutline(Inventory1[7], 0);
	TextDrawFont(Inventory1[7], 4);

	Inventory1[8] = TextDrawCreate(499.999633-202.666717, 394.266662, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory1[8], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[8], 2.999958, 2.488888);
	TextDrawAlignment(Inventory1[8], 1);
	TextDrawColor(Inventory1[8], -37548801);
	TextDrawSetShadow(Inventory1[8], 0);
	TextDrawSetOutline(Inventory1[8], 0);
	TextDrawFont(Inventory1[8], 4);

	Inventory1[9] = TextDrawCreate(399.999694-202.666717, 394.266632, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory1[9], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[9], 2.999958, 2.488888);
	TextDrawAlignment(Inventory1[9], 1);
	TextDrawColor(Inventory1[9], -37548801);
	TextDrawSetShadow(Inventory1[9], 0);
	TextDrawSetOutline(Inventory1[9], 0);
	TextDrawFont(Inventory1[9], 4);

	Inventory1[10] = TextDrawCreate(342.333038-202.666717, 394.266662, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory1[10], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[10], 2.999958, 2.488888);
	TextDrawAlignment(Inventory1[10], 1);
	TextDrawColor(Inventory1[10], -37548801);
	TextDrawSetShadow(Inventory1[10], 0);
	TextDrawSetOutline(Inventory1[10], 0);
	TextDrawFont(Inventory1[10], 4);

	Inventory1[11] = TextDrawCreate(322.000061-202.666717, 400.188903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[11], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[11], 201.666687, 1.244539);
	TextDrawAlignment(Inventory1[11], 1);
	TextDrawColor(Inventory1[11], 336860415);
	TextDrawSetShadow(Inventory1[11], 0);
	TextDrawSetOutline(Inventory1[11], 0);
	TextDrawFont(Inventory1[11], 4);

	Inventory1[12] = TextDrawCreate(322.000061-202.666717, 401.188903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory1[12], 0.000000, 0.000000);
	TextDrawTextSize(Inventory1[12], 201.666687, 1.244539);
	TextDrawAlignment(Inventory1[12], 1);
	TextDrawColor(Inventory1[12], -37548801);
	TextDrawSetShadow(Inventory1[12], 0);
	TextDrawSetOutline(Inventory1[12], 0);
	TextDrawFont(Inventory1[12], 4);

	Inventory1[13] = TextDrawCreate(372.500183-202.666717, 384.703796, "back_page"); // box click buttom back page
	TextDrawLetterSize(Inventory1[13], 0.143332, 0.898964);
	TextDrawTextSize(Inventory1[13], 18.000000, 56.000000);
	TextDrawAlignment(Inventory1[13], 2);
	TextDrawColor(Inventory1[13], -37548801);
	TextDrawUseBox(Inventory1[13], true);
	TextDrawBoxColor(Inventory1[13], -37549056);
	TextDrawSetShadow(Inventory1[13], 0);
	TextDrawSetOutline(Inventory1[13], 0);
	TextDrawBackgroundColor(Inventory1[13], -37549056);
	TextDrawFont(Inventory1[13], 2);
	TextDrawSetProportional(Inventory1[13], 1);
	TextDrawSetSelectable(Inventory1[13], true);

	Inventory1[14] = TextDrawCreate(473.000213-202.666717, 385.118591, "next_page"); // box click buttom next page
	TextDrawLetterSize(Inventory1[14], 0.143332, 0.898963);
	TextDrawTextSize(Inventory1[14], 18.000000, 56.000000);
	TextDrawAlignment(Inventory1[14], 2);
	TextDrawColor(Inventory1[14], -37548801);
	TextDrawUseBox(Inventory1[14], true);
	TextDrawBoxColor(Inventory1[14], -37549056);
	TextDrawSetShadow(Inventory1[14], 0);
	TextDrawSetOutline(Inventory1[14], 0);
	TextDrawBackgroundColor(Inventory1[14], -37549056);
	TextDrawFont(Inventory1[14], 2);
	TextDrawSetProportional(Inventory1[14], 1);
	TextDrawSetSelectable(Inventory1[14], true);


	Inventory1[15] = TextDrawCreate(386.666748-202.666717, 117.637084, "click on an object to interact with it"); // text click on an object to interact with it
	TextDrawLetterSize(Inventory1[15], 0.131991, 0.811847);
	TextDrawAlignment(Inventory1[15], 2);
	TextDrawColor(Inventory1[15], 623191551);
	TextDrawSetShadow(Inventory1[15], 0);
	TextDrawSetOutline(Inventory1[15], 0);
	TextDrawBackgroundColor(Inventory1[15], 255);
	TextDrawFont(Inventory1[15], 2);
	TextDrawSetProportional(Inventory1[15], 1);

	Inventory[0] = TextDrawCreate(321.999877, 111.240676, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[0], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[0], 201.666717, 288.296905);
	TextDrawAlignment(Inventory[0], 1);
	TextDrawColor(Inventory[0], 336860415);
	TextDrawSetShadow(Inventory[0], 0);
	TextDrawSetOutline(Inventory[0], 0);
	TextDrawFont(Inventory[0], 4);

	Inventory[1] = TextDrawCreate(322.000061, 131.133285, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[1], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[1], 201.666702, 1.244541);
	TextDrawAlignment(Inventory[1], 1);
	TextDrawColor(Inventory[1], -37548801);
	TextDrawSetShadow(Inventory[1], 0);
	TextDrawSetOutline(Inventory[1], 0);
	TextDrawFont(Inventory[1], 4);

	Inventory[2] = TextDrawCreate(322.000061, 398.688903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[2], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[2], 201.666702, 1.244541);
	TextDrawAlignment(Inventory[2], 1);
	TextDrawColor(Inventory[2], -37548801);
	TextDrawSetShadow(Inventory[2], 0);
	TextDrawSetOutline(Inventory[2], 0);
	TextDrawFont(Inventory[2], 4);

	Inventory[3] = TextDrawCreate(450.999908, 111.222129, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[3], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[3], 72.666725, 20.326021);
	TextDrawAlignment(Inventory[3], 1);
	TextDrawColor(Inventory[3], -37548801);
	TextDrawSetShadow(Inventory[3], 0);
	TextDrawSetOutline(Inventory[3], 0);
	TextDrawFont(Inventory[3], 4);

	Inventory[4] = TextDrawCreate(467.166748, 116.562973, "inventory"); // Text element
	TextDrawLetterSize(Inventory[4], 0.182332, 1.077334);
	TextDrawAlignment(Inventory[4], 1);
	TextDrawColor(Inventory[4], 336860415);
	TextDrawSetShadow(Inventory[4], 0);
	TextDrawSetOutline(Inventory[4], 0);
	TextDrawBackgroundColor(Inventory[4], 255);
	TextDrawFont(Inventory[4], 2);
	TextDrawSetProportional(Inventory[4], 1);

	Inventory[5] = TextDrawCreate(344.666717, 394.511108, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[5], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[5], 56.666645, 1.659229);
	TextDrawAlignment(Inventory[5], 1);
	TextDrawColor(Inventory[5], -37548801);
	TextDrawSetShadow(Inventory[5], 0);
	TextDrawSetOutline(Inventory[5], 0);
	TextDrawFont(Inventory[5], 4);

	Inventory[6] = TextDrawCreate(444.666717, 394.840759, "LD_SPAC:white"); // box buttom next page of the inventory
	TextDrawLetterSize(Inventory[6], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[6], 56.333312, 1.659229);
	TextDrawAlignment(Inventory[6], 1);
	TextDrawColor(Inventory[6], -37548801);
	TextDrawSetShadow(Inventory[6], 0);
	TextDrawSetOutline(Inventory[6], 0);
	TextDrawFont(Inventory[6], 4);

	Inventory[7] = TextDrawCreate(442.332946, 394.266540, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory[7], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[7], 2.999958, 2.488888);
	TextDrawAlignment(Inventory[7], 1);
	TextDrawColor(Inventory[7], -37548801);
	TextDrawSetShadow(Inventory[7], 0);
	TextDrawSetOutline(Inventory[7], 0);
	TextDrawFont(Inventory[7], 4);

	Inventory[8] = TextDrawCreate(499.999633, 394.266662, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory[8], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[8], 2.999958, 2.488888);
	TextDrawAlignment(Inventory[8], 1);
	TextDrawColor(Inventory[8], -37548801);
	TextDrawSetShadow(Inventory[8], 0);
	TextDrawSetOutline(Inventory[8], 0);
	TextDrawFont(Inventory[8], 4);

	Inventory[9] = TextDrawCreate(399.999694, 394.266632, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory[9], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[9], 2.999958, 2.488888);
	TextDrawAlignment(Inventory[9], 1);
	TextDrawColor(Inventory[9], -37548801);
	TextDrawSetShadow(Inventory[9], 0);
	TextDrawSetOutline(Inventory[9], 0);
	TextDrawFont(Inventory[9], 4);

	Inventory[10] = TextDrawCreate(342.333038, 394.266662, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(Inventory[10], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[10], 2.999958, 2.488888);
	TextDrawAlignment(Inventory[10], 1);
	TextDrawColor(Inventory[10], -37548801);
	TextDrawSetShadow(Inventory[10], 0);
	TextDrawSetOutline(Inventory[10], 0);
	TextDrawFont(Inventory[10], 4);

	Inventory[11] = TextDrawCreate(322.000061, 400.188903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[11], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[11], 201.666687, 1.244539);
	TextDrawAlignment(Inventory[11], 1);
	TextDrawColor(Inventory[11], 336860415);
	TextDrawSetShadow(Inventory[11], 0);
	TextDrawSetOutline(Inventory[11], 0);
	TextDrawFont(Inventory[11], 4);

	Inventory[12] = TextDrawCreate(322.000061, 401.188903, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[12], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[12], 201.666687, 1.244539);
	TextDrawAlignment(Inventory[12], 1);
	TextDrawColor(Inventory[12], -37548801);
	TextDrawSetShadow(Inventory[12], 0);
	TextDrawSetOutline(Inventory[12], 0);
	TextDrawFont(Inventory[12], 4);

	Inventory[13] = TextDrawCreate(372.500183, 384.703796, "back_page"); // box click buttom back page
	TextDrawLetterSize(Inventory[13], 0.143332, 0.898964);
	TextDrawTextSize(Inventory[13], 18.000000, 56.000000);
	TextDrawAlignment(Inventory[13], 2);
	TextDrawColor(Inventory[13], -37548801);
	TextDrawUseBox(Inventory[13], true);
	TextDrawBoxColor(Inventory[13], -37549056);
	TextDrawSetShadow(Inventory[13], 0);
	TextDrawSetOutline(Inventory[13], 0);
	TextDrawBackgroundColor(Inventory[13], -37549056);
	TextDrawFont(Inventory[13], 2);
	TextDrawSetProportional(Inventory[13], 1);
	TextDrawSetSelectable(Inventory[13], true);

	Inventory[14] = TextDrawCreate(473.000213, 385.118591, "next_page"); // box click buttom next page
	TextDrawLetterSize(Inventory[14], 0.143332, 0.898963);
	TextDrawTextSize(Inventory[14], 18.000000, 56.000000);
	TextDrawAlignment(Inventory[14], 2);
	TextDrawColor(Inventory[14], -37548801);
	TextDrawUseBox(Inventory[14], true);
	TextDrawBoxColor(Inventory[14], -37549056);
	TextDrawSetShadow(Inventory[14], 0);
	TextDrawSetOutline(Inventory[14], 0);
	TextDrawBackgroundColor(Inventory[14], -37549056);
	TextDrawFont(Inventory[14], 2);
	TextDrawSetProportional(Inventory[14], 1);
	TextDrawSetSelectable(Inventory[14], true);

	Inventory[15] = TextDrawCreate(194.166442, 132.066635, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[15], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[15], 126.666755, 204.089447);
	TextDrawAlignment(Inventory[15], 1);
	TextDrawColor(Inventory[15], 336860415);
	TextDrawSetShadow(Inventory[15], 0);
	TextDrawSetOutline(Inventory[15], 0);
	TextDrawFont(Inventory[15], 4);

	Inventory[16] = TextDrawCreate(320.833435, 132.318511, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[16], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[16], 1.000036, 270.459594);
	TextDrawAlignment(Inventory[16], 1);
	TextDrawColor(Inventory[16], -37548801);
	TextDrawSetShadow(Inventory[16], 0);
	TextDrawSetOutline(Inventory[16], 0);
	TextDrawFont(Inventory[16], 4);

	Inventory[17] = TextDrawCreate(249.833236, 132.292480, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[17], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[17], 71.000053, 20.326021);
	TextDrawAlignment(Inventory[17], 1);
	TextDrawColor(Inventory[17], -37548801);
	TextDrawSetShadow(Inventory[17], 0);
	TextDrawSetOutline(Inventory[17], 0);
	TextDrawFont(Inventory[17], 4);

	Inventory[18] = TextDrawCreate(194.166793, 152.288879, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[18], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[18], 127.333328, 1.244541);
	TextDrawAlignment(Inventory[18], 1);
	TextDrawColor(Inventory[18], -37548801);
	TextDrawSetShadow(Inventory[18], 0);
	TextDrawSetOutline(Inventory[18], 0);
	TextDrawFont(Inventory[18], 4);

	Inventory[19] = TextDrawCreate(270.833557, 138.133377, "player"); // just text player
	TextDrawLetterSize(Inventory[19], 0.182330, 1.077334);
	TextDrawAlignment(Inventory[19], 1);
	TextDrawColor(Inventory[19], 336860415);
	TextDrawSetShadow(Inventory[19], 0);
	TextDrawSetOutline(Inventory[19], 0);
	TextDrawBackgroundColor(Inventory[19], 255);
	TextDrawFont(Inventory[19], 2);
	TextDrawSetProportional(Inventory[19], 1);

	Inventory[20] = TextDrawCreate(250.000000, 219.885177, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[20], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[20], 46.333343, 5.392590);
	TextDrawAlignment(Inventory[20], 1);
	TextDrawColor(Inventory[20], 589505535);
	TextDrawSetShadow(Inventory[20], 0);
	TextDrawSetOutline(Inventory[20], 0);
	TextDrawFont(Inventory[20], 4);

	Inventory[21] = TextDrawCreate(245.666625, 220.277725, "LD_SPAC:white"); // object burger
	TextDrawLetterSize(Inventory[21], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[21], 17.333330, 24.059265);
	TextDrawAlignment(Inventory[21], 1);
	TextDrawColor(Inventory[21], -1);
	TextDrawUseBox(Inventory[21], true);
	TextDrawBoxColor(Inventory[21], -37549056);
	TextDrawSetShadow(Inventory[21], 0);
	TextDrawSetOutline(Inventory[21], 0);
	TextDrawBackgroundColor(Inventory[21], -37549056);
	TextDrawFont(Inventory[21], 5);
	TextDrawSetPreviewModel(Inventory[21], 2703);
	TextDrawSetPreviewRot(Inventory[21], 270.000000, 70.000000, 0.000000, 1.000000);

	Inventory[22] = TextDrawCreate(386.666748, 117.637084, "click on an object to interact with it"); // text click on an object to interact with it
	TextDrawLetterSize(Inventory[22], 0.131991, 0.811847);
	TextDrawAlignment(Inventory[22], 2);
	TextDrawColor(Inventory[22], 623191551);
	TextDrawSetShadow(Inventory[22], 0);
	TextDrawSetOutline(Inventory[22], 0);
	TextDrawBackgroundColor(Inventory[22], 255);
	TextDrawFont(Inventory[22], 2);
	TextDrawSetProportional(Inventory[22], 1);

	Inventory[23] = TextDrawCreate(220.500076, 132.700057, "LD_SPAC:white"); // object armour
	TextDrawLetterSize(Inventory[23], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[23], 16.000001, 20.740749);
	TextDrawAlignment(Inventory[23], 1);
	TextDrawColor(Inventory[23], -1);
	TextDrawUseBox(Inventory[23], true);
	TextDrawBoxColor(Inventory[23], -37549056);
	TextDrawSetShadow(Inventory[23], 0);
	TextDrawSetOutline(Inventory[23], 0);
	TextDrawBackgroundColor(Inventory[23], -37549056);
	TextDrawFont(Inventory[23], 5);
	TextDrawSetPreviewModel(Inventory[23], 19515);
	TextDrawSetPreviewRot(Inventory[23], 0.000000, 270.000000, 35.000000, 1.000000);

	Inventory[24] = TextDrawCreate(195.000061, 134.388916, "LD_SPAC:white"); // object heart
	TextDrawLetterSize(Inventory[24], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[24], 13.000000, 16.177787);
	TextDrawAlignment(Inventory[24], 1);
	TextDrawColor(Inventory[24], -1);
	TextDrawUseBox(Inventory[24], true);
	TextDrawBoxColor(Inventory[24], -37549056);
	TextDrawSetShadow(Inventory[24], 0);
	TextDrawSetOutline(Inventory[24], 0);
	TextDrawBackgroundColor(Inventory[24], -37549056);
	TextDrawFont(Inventory[24], 5);
	TextDrawSetPreviewModel(Inventory[24], 1240);
	TextDrawSetPreviewRot(Inventory[24], 0.000000, 0.000000, 0.000000, 1.000000);

	Inventory[25] = TextDrawCreate(195.833312, 247.981445, "LD_SPAC:white"); // buttom menu
	TextDrawLetterSize(Inventory[25], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[25], 60.999984, 21.570350);
	TextDrawAlignment(Inventory[25], 1);
	TextDrawColor(Inventory[25], -37548801);
	TextDrawUseBox(Inventory[25], true);
	TextDrawBoxColor(Inventory[25], 255);
	TextDrawSetShadow(Inventory[25], 0);
	TextDrawSetOutline(Inventory[25], 0);
	TextDrawFont(Inventory[25], 4);
	TextDrawSetSelectable(Inventory[25], true);

	Inventory[26] = TextDrawCreate(195.833267, 271.296264, "LD_SPAC:white"); // buttom gps
	TextDrawLetterSize(Inventory[26], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[26], 60.999984, 21.570350);
	TextDrawAlignment(Inventory[26], 1);
	TextDrawColor(Inventory[26], -979959041);
	TextDrawUseBox(Inventory[26], true);
	TextDrawBoxColor(Inventory[26], 255);
	TextDrawSetShadow(Inventory[26], 0);
	TextDrawSetOutline(Inventory[26], 0);
	TextDrawFont(Inventory[26], 4);
	TextDrawSetSelectable(Inventory[26], true);

	Inventory[27] = TextDrawCreate(258.499908, 271.296234, "LD_SPAC:white"); // buttom help
	TextDrawLetterSize(Inventory[27], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[27], 60.999984, 21.570350);
	TextDrawAlignment(Inventory[27], 1);
	TextDrawColor(Inventory[27], -979959041);
	TextDrawUseBox(Inventory[27], true);
	TextDrawBoxColor(Inventory[27], 255);
	TextDrawSetShadow(Inventory[27], 0);
	TextDrawSetOutline(Inventory[27], 0);
	TextDrawFont(Inventory[27], 4);
	TextDrawSetSelectable(Inventory[27], true);

	Inventory[28] = TextDrawCreate(195.833267, 295.025878, "LD_SPAC:white"); // buttom donate
	TextDrawLetterSize(Inventory[28], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[28], 60.999984, 21.570350);
	TextDrawAlignment(Inventory[28], 1);
	TextDrawColor(Inventory[28], -1922235905);
	TextDrawUseBox(Inventory[28], true);
	TextDrawBoxColor(Inventory[28], 255);
	TextDrawSetShadow(Inventory[28], 0);
	TextDrawSetOutline(Inventory[28], 0);
	TextDrawFont(Inventory[28], 4);
	TextDrawSetSelectable(Inventory[28], true);

	Inventory[29] = TextDrawCreate(258.499877, 295.111022, "LD_SPAC:white"); // buttom exit
	TextDrawLetterSize(Inventory[29], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[29], 60.999984, 21.570350);
	TextDrawAlignment(Inventory[29], 1);
	TextDrawColor(Inventory[29], -1922235905);
	TextDrawUseBox(Inventory[29], true);
	TextDrawBoxColor(Inventory[29], 255);
	TextDrawSetShadow(Inventory[29], 0);
	TextDrawSetOutline(Inventory[29], 0);
	TextDrawFont(Inventory[29], 4);
	TextDrawSetSelectable(Inventory[29], true);

	Inventory[30] = TextDrawCreate(225.333480, 254.525985, "menu"); // percent of hp
	TextDrawLetterSize(Inventory[30], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[30], 2);
	TextDrawColor(Inventory[30], 336860415);
	TextDrawSetShadow(Inventory[30], 0);
	TextDrawSetOutline(Inventory[30], 0);
	TextDrawBackgroundColor(Inventory[30], 255);
	TextDrawFont(Inventory[30], 2);
	TextDrawSetProportional(Inventory[30], 1);

	Inventory[31]  = TextDrawCreate( 258.666656, 247.981475, "LD_SPAC:white"); // buttom report
	TextDrawLetterSize(Inventory[31]  , 0.000000, 0.000000);
	TextDrawTextSize(Inventory[31],  60.999984, 21.570350);
	TextDrawAlignment(Inventory[31] , 1);
	TextDrawColor(Inventory[31] , -37548801);
	TextDrawSetShadow(Inventory[31] , 0);
	TextDrawSetOutline(Inventory[31] , 0);
	TextDrawFont(Inventory[31] , 4);
	TextDrawSetSelectable(Inventory[31], true);

	Inventory[32] = TextDrawCreate(225.333480, 277.840820, "gps"); // percent of hp
	TextDrawLetterSize(Inventory[32], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[32], 2);
	TextDrawColor(Inventory[32], 336860415);
	TextDrawSetShadow(Inventory[32], 0);
	TextDrawSetOutline(Inventory[32], 0);
	TextDrawBackgroundColor(Inventory[32], 255);
	TextDrawFont(Inventory[32], 2);
	TextDrawSetProportional(Inventory[32], 1);

	Inventory[33] = TextDrawCreate(288.833465, 277.511138, "help"); // percent of hp
	TextDrawLetterSize(Inventory[33], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[33], 2);
	TextDrawColor(Inventory[33], 336860415);
	TextDrawSetShadow(Inventory[33], 0);
	TextDrawSetOutline(Inventory[33], 0);
	TextDrawBackgroundColor(Inventory[33], 255);
	TextDrawFont(Inventory[33], 2);
	TextDrawSetProportional(Inventory[33], 1);

	Inventory[34] = TextDrawCreate(225.666824, 301.400146, "donate"); // percent of hp
	TextDrawLetterSize(Inventory[34], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[34], 2);
	TextDrawColor(Inventory[34], 336860415);
	TextDrawSetShadow(Inventory[34], 0);
	TextDrawSetOutline(Inventory[34], 0);
	TextDrawBackgroundColor(Inventory[34], 255);
	TextDrawFont(Inventory[34], 2);
	TextDrawSetProportional(Inventory[34], 1);

	Inventory[35] = TextDrawCreate(288.166839, 301.400115, "close"); // percent of hp
	TextDrawLetterSize(Inventory[35], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[35], 2);
	TextDrawColor(Inventory[35], 336860415);
	TextDrawSetShadow(Inventory[35], 0);
	TextDrawSetOutline(Inventory[35], 0);
	TextDrawBackgroundColor(Inventory[35], 255);
	TextDrawFont(Inventory[35], 2);
	TextDrawSetProportional(Inventory[35], 1);

	Inventory[36] = TextDrawCreate(194.333404, 333.159332, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[36], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[36], 126.933433, 1.244539);
	TextDrawAlignment(Inventory[36], 1);
	TextDrawColor(Inventory[36], -37548801);
	TextDrawSetShadow(Inventory[36], 0);
	TextDrawSetOutline(Inventory[36], 0);
	TextDrawFont(Inventory[36], 4);

	Inventory[37] = TextDrawCreate(194.333404, 336.159332, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(Inventory[37], 0.000000, 0.000000);
	TextDrawTextSize(Inventory[37], 126.933433, 1.244539);
	TextDrawAlignment(Inventory[37], 1);
	TextDrawColor(Inventory[37], -37548801);
	TextDrawSetShadow(Inventory[37], 0);
	TextDrawSetOutline(Inventory[37], 0);
	TextDrawFont(Inventory[37], 4);

	Inventory[38] = TextDrawCreate(289.333496, 254.525985, "report"); // percent of hp
	TextDrawLetterSize(Inventory[38], 0.149993, 0.969479);
	TextDrawAlignment(Inventory[38], 2);
	TextDrawColor(Inventory[38], 336860415);
	TextDrawSetShadow(Inventory[38], 0);
	TextDrawSetOutline(Inventory[38], 0);
	TextDrawBackgroundColor(Inventory[38], 255);
	TextDrawFont(Inventory[38], 2);
	TextDrawSetProportional(Inventory[38], 1);


	TexturesLoading[0] = TextDrawCreate(0.000000, 0.000000, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(TexturesLoading[0], 0.000000, 0.000000);
	TextDrawTextSize(TexturesLoading[0], 640.000000, 448.000000);
	TextDrawAlignment(TexturesLoading[0], 1);
	TextDrawColor(TexturesLoading[0], 255);
	TextDrawSetShadow(TexturesLoading[0], 0);
	TextDrawSetOutline(TexturesLoading[0], 0);
	TextDrawFont(TexturesLoading[0], 4);

	TexturesLoading[1] = TextDrawCreate(211.666625, 418.555541, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(TexturesLoading[1], 0.000000, 0.000000);
	TextDrawTextSize(TexturesLoading[1], 205.666656, 12.444458);
	TextDrawAlignment(TexturesLoading[1], 1);
	TextDrawColor(TexturesLoading[1], 1162167807);
	TextDrawSetShadow(TexturesLoading[1], 0);
	TextDrawSetOutline(TexturesLoading[1], 0);
	TextDrawFont(TexturesLoading[1], 4);

	TexturesLoading[2] = TextDrawCreate(225.499923, 403.540771, "TEXTURES LOADING, PLEASE WAIT..."); // Text element
	TextDrawLetterSize(TexturesLoading[2], 0.256332, 1.496297);
	TextDrawAlignment(TexturesLoading[2], 1);
	TextDrawColor(TexturesLoading[2], -1);
	TextDrawSetShadow(TexturesLoading[2], 1);
	TextDrawSetOutline(TexturesLoading[2], 0);
	TextDrawBackgroundColor(TexturesLoading[2], 51);
	TextDrawFont(TexturesLoading[2], 2);
	TextDrawSetProportional(TexturesLoading[2], 1);

	TexturesLoading[3] = TextDrawCreate(252.333221, 218.203598, "maryland-rp.ru"); // Text element
	TextDrawLetterSize(TexturesLoading[3], 0.376666, 2.197334);
	TextDrawAlignment(TexturesLoading[3], 1);
	TextDrawColor(TexturesLoading[3], -36827905);
	TextDrawSetShadow(TexturesLoading[3], 1);
	TextDrawSetOutline(TexturesLoading[3], 0);
	TextDrawBackgroundColor(TexturesLoading[3], 51);
	TextDrawFont(TexturesLoading[3], 2);
	TextDrawSetProportional(TexturesLoading[3], 1);

	TexturesLoading[4] = TextDrawCreate(251.999893, 210.855453, "VISIT_OUR_WEBSITE"); // Text element
	TextDrawLetterSize(TexturesLoading[4], 0.221331, 1.409185);
	TextDrawAlignment(TexturesLoading[4], 1);
	TextDrawColor(TexturesLoading[4], -1936945921);
	TextDrawSetShadow(TexturesLoading[4], 1);
	TextDrawSetOutline(TexturesLoading[4], 0);
	TextDrawBackgroundColor(TexturesLoading[4], 51);
	TextDrawFont(TexturesLoading[4], 2);
	TextDrawSetProportional(TexturesLoading[4], 1);

	TexturesLoading[5] = TextDrawCreate(251.833328, 236.944458, "LD_SPAC:white"); // Texture element
	TextDrawLetterSize(TexturesLoading[5], 0.000000, 0.000000);
	TextDrawTextSize(TexturesLoading[5], 126.999992, 1.659260);
	TextDrawAlignment(TexturesLoading[5], 1);
	TextDrawColor(TexturesLoading[5], -36827905);
	TextDrawSetShadow(TexturesLoading[5], 0);
	TextDrawSetOutline(TexturesLoading[5], 0);
	TextDrawFont(TexturesLoading[5], 4);

	TexturesLoading[6] = TextDrawCreate(247.500000, 236.444427, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(TexturesLoading[6], 0.000000, 0.000000);
	TextDrawTextSize(TexturesLoading[6], 5.666707, 2.903669);
	TextDrawAlignment(TexturesLoading[6], 1);
	TextDrawColor(TexturesLoading[6], -36827905);
	TextDrawSetShadow(TexturesLoading[6], 0);
	TextDrawSetOutline(TexturesLoading[6], 0);
	TextDrawFont(TexturesLoading[6], 4);

	TexturesLoading[7] = TextDrawCreate(377.500000, 236.444427, "LD_BEAT:chit"); // Texture element
	TextDrawLetterSize(TexturesLoading[7], 0.000000, 0.000000);
	TextDrawTextSize(TexturesLoading[7], 5.666707, 2.903669);
	TextDrawAlignment(TexturesLoading[7], 1);
	TextDrawColor(TexturesLoading[7], -36827905);
	TextDrawSetShadow(TexturesLoading[7], 0);
	TextDrawSetOutline(TexturesLoading[7], 0);
	TextDrawFont(TexturesLoading[7], 4);

